(function(g){var window=this;/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
var A2=function(a){a.T("cardstatechange",g.dL(a)&&g.eL(a)?1:0)},Esa=function(a){if(/-[a-z]/.test("pollChoiceIndex"))return null;
if(g.ak&&a.dataset){if(g.Oc()&&!("pollChoiceIndex"in a.dataset))return null;a=a.dataset.pollChoiceIndex;return void 0===a?null:a}return a.getAttribute("data-"+g.jd("pollChoiceIndex"))},Fsa=function(a){return Math.pow(a,3)},Gsa=function(a){return 3*a*a-2*a*a*a},B2=function(a,b){var c=g.yo("use_default_events_client")?void 0:g.Fq;
(0,g.x)(b,function(d){d={csn:a,ve:g.Mr(d),eventType:4};var e={tl:g.Tr(a),lj:a};"UNDEFINED_CSN"==a?g.fs("visualElementShown",d,e):c?g.Vp("visualElementShown",d,c,e):g.Gq("visualElementShown",d,e)})},C2=function(a,b){var c=g.yo("use_default_events_client")?void 0:g.Fq;
(0,g.x)(b,function(d){var e=void 0;e=void 0===e?!1:e;d={csn:a,ve:g.Mr(d),eventType:e?16:8};e={tl:g.Tr(a),lj:a,EE:e};"UNDEFINED_CSN"==a?g.fs("visualElementHidden",d,e):c?g.Vp("visualElementHidden",d,c,e):g.Gq("visualElementHidden",d,e)})},F2=function(a){a=g.Pa(a);
delete D2[a];g.Mb(D2)&&E2&&E2.stop()},Isa=function(){E2||(E2=new g.H(function(){Hsa()},20));
var a=E2;a.isActive()||a.start()},Hsa=function(){var a=(0,g.B)();
g.zb(D2,function(b){Jsa(b,a)});
g.Mb(D2)||Isa()},G2=function(a,b,c,d){g.Gn.call(this);
if(!Array.isArray(a)||!Array.isArray(b))throw Error("Start and end parameters must be arrays");if(a.length!=b.length)throw Error("Start and end points must be the same length");this.A=a;this.H=b;this.duration=c;this.D=d;this.coords=[];this.progress=this.G=0;this.C=null},Jsa=function(a,b){b<a.startTime&&(a.endTime=b+a.endTime-a.startTime,a.startTime=b);
a.progress=(b-a.startTime)/(a.endTime-a.startTime);1<a.progress&&(a.progress=1);a.G=1E3/(b-a.C);a.C=b;Ksa(a,a.progress);1==a.progress?(a.o=0,F2(a),a.Ic(),a.zm()):a.fb()&&a.Yt()},Ksa=function(a,b){g.Ma(a.D)&&(b=a.D(b));
a.coords=Array(a.A.length);for(var c=0;c<a.A.length;c++)a.coords[c]=(a.H[c]-a.A[c])*b+a.A[c]},Lsa=function(a,b){g.Je.call(this,a);
this.coords=b.coords;this.x=b.coords[0];this.y=b.coords[1];this.z=b.coords[2];this.duration=b.duration;this.progress=b.progress;this.fps=b.G;this.state=b.o},H2=function(a,b,c,d,e){G2.call(this,b,c,d,e);
this.element=a},I2=function(a,b,c,d,e){if(2!=b.length||2!=c.length)throw Error("Start and end points must be 2D");
H2.call(this,a,b,c,d,e)},J2=function(a){g.z.call(this);
this.u=a||window;this.o=[]},Msa=function(a,b,c,d){c=(0,g.w)(c,d||a.u);
b=g.np(b,"change",c,"iv-card-poll-choice-input");a.o.push(b)},K2=function(a){return a.baseUrl||null},L2=function(a,b){return(0,g.ue)((0,g.Dc)(a,b,void 0),function(c){return!!c})},Nsa=function(a,b,c){function d(ub){var nb=ub.hovercardButton;
if(!nb)return null;nb=nb.subscribeButtonRenderer;if(!nb)return null;var $d=f(nb.unsubscribedButtonText),tf=f(nb.subscribedButtonText);if(nb.subscribed){var Sh=f(nb.subscriberCountWithUnsubscribeText);var Th=f(nb.subscriberCountText)}else Sh=f(nb.subscriberCountText),Th=f(nb.subscriberCountWithSubscribeText);var eg=null;return ub.signinEndpoint&&(eg=g.Hb(ub,"signinEndpoint","webNavigationEndpointData","url"),!eg)?null:$d&&(tf||eg)?{subscribed:nb.subscribed,subscribeText:$d,subscribeCount:Sh,unsubscribeText:tf,
unsubscribeCount:Th,enabled:nb.enabled,signinUrl:eg,classic:ub.useClassicSubscribeButton}:null}
function e(ub){if(ub){var nb=[],$d=ub.videoId;$d&&nb.push("v="+$d);($d=ub.playlistId)&&nb.push("list="+$d);(ub=ub.startTimeSeconds)&&nb.push("t="+ub);return"/watch?"+nb.join("&")}}
function f(ub){if(!ub)return null;var nb=ub.simpleText;return nb?nb:ub.runs?(0,g.Dc)(ub.runs,function($d){return $d.text}).join(""):null}
b=b.endscreenElementRenderer;if(!b)return null;var k=b.style,l=b.endpoint||{},m=null,n=null,q=null,t=null,u=null,y=null,C=!1,D=null,E=null,F=null,G=null,ha=null;if("VIDEO"==k)m=l.urlEndpoint?l.urlEndpoint.url:e(l.watchEndpoint),n=!1,q=a,t=f(b.videoDuration);else if("PLAYLIST"==k)m=l.urlEndpoint?l.urlEndpoint.url:e(l.watchEndpoint),n=!1,q=a,u=f(b.playlistLength);else if("CHANNEL"==k){if(C=g.Hb(l,"browseEndpoint","browseId"))y=C,m="/channel/"+y;n=!1;q="new";(C=!!b.isSubscribe)?D=d(b):E=f(b.subscribersText)}else"WEBSITE"==
k?((F=g.Hb(l,"urlEndpoint","url"))&&(m=F),n=!0,q="new",F=b.icon.thumbnails[0].url):"CREATOR_MERCHANDISE"==k&&(b.productPrice&&(G=f(b.productPrice)),b.additionalFeesText&&(ha=f(b.additionalFeesText)),(n=g.Hb(l,"urlEndpoint","url"))&&(m=n),n=!0,q="new");a=g.Hb(b,"title","accessibility","accessibilityData","label");var na=b.endpoint?b.endpoint.clickTrackingParams:null,cc="";if(b.metadata){var vc=f(b.metadata);vc&&(cc=vc)}return{id:"element-"+c,type:k,title:f(b.title),metadata:cc,callToAction:f(b.callToAction),
Vw:b.image,iconUrl:F,left:parseFloat(b.left),width:parseFloat(b.width),top:parseFloat(b.top),aspectRatio:parseFloat(b.aspectRatio),startMs:parseInt(b.startMs,10),endMs:parseInt(b.endMs,10),videoDuration:t,playlistLength:u,channelId:y,subscribeButton:D,subscribersText:E,isSubscribe:C,targetUrl:m,bG:n,Qb:{itct:na},yO:q,jl:a?a:null,fG:b.isPlaceholder,impressionUrls:L2(b.impressionUrls||[],K2),TF:L2(b.hovercardShowUrls||[],K2),clickUrls:L2(l.loggingUrls||[],K2),visualElement:g.Kr(b.trackingParams),productPrice:G,
additionalFeesText:ha}},M2=function(a,b){var c={};
c.startMs=parseInt(a.startMs,10);c.impressionUrls=L2(a.impressionUrls||[],K2);a.trackingParams&&(c.visualElement=g.Kr(a.trackingParams));c.elements=L2(a.elements||[],function(d,e){return Nsa(b,d,e)});
return c},N2=function(a){g.BL.call(this,a);
this.B=this.u=null;this.o={};this.G={};this.D=this.A=null;this.J=[];a=a.O();this.R=g.Hy(a)||g.Jy(a);this.N=!0;this.H=0;this.C=new g.ur(this);g.A(this,this.C);this.C.M(this.player,g.bC("creatorendscreen"),this.PG);this.C.M(this.player,"crx_creatorendscreen",this.QG);this.C.M(this.player,"resize",this.dz);this.C.M(window,"focus",this.zN);this.load();var b=g.oe("STYLE");(document.getElementsByTagName("HEAD")[0]||document.body).appendChild(b);g.Ge(this,function(){g.te(b)});
b.sheet&&(b.sheet.insertRule(".ytp-ce-playlist-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASBAMAAACk4JNkAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAIVBMVEVMaXGzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7P///91E4wTAAAACXRSTlMArBbpVOtYrReN+x2FAAAAAWJLR0QKaND0VgAAACFJREFUCNdjYCAWzIQAFBaZ6hgVYLKcJnBWGEyWvYGASwCXtBf7m4i3CQAAAABJRU5ErkJggg==) no-repeat center;background-size:18px;width:18px;height:18px}",0),b.sheet.insertRule(".ytp-ce-size-853 .ytp-ce-playlist-icon, .ytp-ce-size-1280 .ytp-ce-playlist-icon, .ytp-ce-size-1920 .ytp-ce-playlist-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYBAMAAAASWSDLAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJ1BMVEVMaXGzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7P///9RfzIKAAAAC3RSTlMAvDeyLvxYtDK9Ogx4T1QAAAABYktHRAyBs1FjAAAAK0lEQVQY02NgoBjshgO8HJoYwKiAMGAD92YHJM7uMCTO9gaEHs4FlPuZAQC8Fj8x/xHjxwAAAABJRU5ErkJggg==) no-repeat center;background-size:24px;width:24px;height:24px}",
0))},Osa=function(a){return a.player.getVideoData().oc?"current":a.R?"new":"current"},O2=function(a){return"creator-endscreen-editor"===a.player.O().playerStyle},P2=function(a,b,c){c=void 0===c?!0:c;
g.tR(a.player.app,"creatorendscreen",void 0);a.A&&(a.A.dispose(),a.A=null,a.D.dispose(),a.D=null);for(var d in a.o)a.o[d].dispose();a.o={};a.G={};0<a.J.length&&(a.J.forEach(function(l){l.dispose()}),a.J.length=0);
a.H=0;if((a.u=b)&&b.elements){c&&Psa(a);c=[];d=new g.ZB(b.startMs,0x7ffffffffffff,{id:"ytp-ce-in-endscreen",namespace:"creatorendscreen"});c.push(d);a.player.O().o||(a.A=new g.Q({F:"div",I:"ytp-ce-shadow"}),g.oL(a.player,a.A.element,4),a.D=new g.jN(a.A,200));for(d=0;d<b.elements.length;++d){var e=b.elements[d],f=Qsa(a,e);a.o[e.id]=f;a.G[e.id]=e;g.oL(a.player,f.element,4);var k=new g.ZB(e.startMs,e.endMs,{id:"ytp-ce-element-"+e.id,namespace:"creatorendscreen"});c.push(k);Rsa(a,f,e)}g.kL(a.player,c);
a.dz()}},Psa=function(a){var b=g.Qr(),c=g.Sr();
c&&b&&a.u.visualElement&&g.ls(c,b,a.u.visualElement)},Qsa=function(a,b){var c=null;
switch(b.type){case "VIDEO":c={F:"div",Z:["ytp-ce-element","ytp-ce-video"],P:{tabindex:"0","aria-label":b.jl||"","aria-hidden":"true"},L:[{F:"div",I:"ytp-ce-element-shadow"},{F:"div",I:"ytp-ce-covering-image",P:Q2(b)},{F:"div",I:"ytp-ce-covering-shadow-top"},{F:"a",I:"ytp-ce-covering-overlay",P:{href:R2(a,b.targetUrl),tabindex:"-1"},L:[{F:"div",Z:["ytp-ce-video-title","yt-ui-ellipsis","yt-ui-ellipsis-2"],P:{dir:g.Mn(b.title||"")},X:b.title},{F:"div",I:"ytp-ce-video-duration",X:b.videoDuration}]}]};
c=new g.Q(c);break;case "PLAYLIST":c={F:"div",Z:["ytp-ce-element","ytp-ce-playlist"],P:{tabindex:"0","aria-label":b.jl||"","aria-hidden":"true"},L:[{F:"div",I:"ytp-ce-element-shadow"},{F:"div",I:"ytp-ce-covering-image",P:Q2(b)},{F:"div",I:"ytp-ce-covering-shadow-top"},{F:"a",I:"ytp-ce-covering-overlay",P:{href:R2(a,b.targetUrl),tabindex:"-1"},L:[{F:"div",Z:["ytp-ce-playlist-title","yt-ui-ellipsis","yt-ui-ellipsis-2"],P:{dir:g.Mn(b.title||"")},X:b.title},{F:"div",I:"ytp-ce-playlist-count",L:[{F:"div",
I:"ytp-ce-playlist-icon"},{F:"div",I:"ytp-ce-playlist-count-text",X:b.playlistLength}]}]}]};c=new g.Q(c);break;case "CHANNEL":c={F:"div",Z:["ytp-ce-element","ytp-ce-channel",b.isSubscribe?"ytp-ce-channel-this":"ytp-ce-channel-that"],P:{tabindex:"0","aria-label":b.jl||"","aria-hidden":"true"},L:[{F:"div",I:"ytp-ce-element-shadow"},{F:"div",I:"ytp-ce-expanding-overlay",L:[{F:"div",I:"ytp-ce-expanding-overlay-hider"},{F:"div",I:"ytp-ce-expanding-overlay-background"},{F:"div",I:"ytp-ce-expanding-overlay-content",
L:[{F:"div",I:"ytp-ce-expanding-overlay-body",L:[{F:"div",I:"ytp-ce-expanding-overlay-body-padding",L:[{F:"a",Z:["ytp-ce-channel-title","ytp-ce-link"],P:{href:R2(a,b.targetUrl),target:"_blank",tabindex:"-1",dir:g.Mn(b.title||"")},X:b.title},b.subscribeButton?{F:"div",I:"ytp-ce-subscribe-container",L:[{F:"div",I:"ytp-ce-channel-subscribe"}]}:"",b.subscribersText?{F:"div",I:"ytp-ce-channel-subscribers-text",X:b.subscribersText}:"",b.metadata?{F:"div",Z:["ytp-ce-channel-metadata","yt-ui-ellipsis","yt-ui-ellipsis-3"],
X:b.metadata}:""]}]}]}]},{F:"div",I:"ytp-ce-expanding-image",P:Q2(b)}]};c=new g.Q(c);var d=g.ae(document,"div","ytp-ce-channel-subscribe",c.element)[0];if(b.subscribeButton&&b.channelId){g.I(d,"ytp-ce-subscribe-button");if(a.player.O().o){var e=null;var f=b.Qb.itct}else e="endscreen",f=null;e=new g.wQ(b.subscribeButton.subscribeText,b.subscribeButton.subscribeCount,b.subscribeButton.unsubscribeText,b.subscribeButton.unsubscribeCount,b.subscribeButton.enabled,b.subscribeButton.classic,b.channelId,
!!b.subscribeButton.subscribed,e,f,b.subscribeButton.signinUrl,a.player);d.appendChild(e.element);a.J.push(e)}break;case "WEBSITE":c={F:"div",Z:["ytp-ce-element","ytp-ce-website"],P:{tabindex:"0","aria-label":b.jl||"","aria-hidden":"true"},L:[{F:"div",I:"ytp-ce-element-shadow"},{F:"div",I:"ytp-ce-expanding-overlay",L:[{F:"div",I:"ytp-ce-expanding-overlay-hider"},{F:"div",I:"ytp-ce-expanding-overlay-background"},{F:"div",I:"ytp-ce-expanding-overlay-content",L:[{F:"div",I:"ytp-ce-expanding-overlay-body",
L:[{F:"div",I:"ytp-ce-expanding-overlay-body-padding",L:[{F:"div",I:"ytp-ce-website-title",P:{dir:g.Mn(b.title||"")},X:b.title},{F:"div",I:"ytp-ce-website-metadata",X:b.metadata},{F:"a",Z:["ytp-ce-website-goto","ytp-ce-link"],P:{href:R2(a,b.targetUrl),target:"_blank",tabindex:"-1"},X:b.callToAction}]}]}]}]},{F:"div",I:"ytp-ce-expanding-image",P:Q2(b)},{F:"div",I:"ytp-ce-expanding-icon",P:Ssa(b.iconUrl)}]};c=new g.Q(c);break;case "CREATOR_MERCHANDISE":c="",b.productPrice&&(c={F:"div",I:"ytp-ce-merchandise-price-container",
L:[{F:"div",I:"ytp-ce-merchandise-price",X:b.productPrice}]},b.additionalFeesText&&c.L.push({F:"div",I:"ytp-ce-merchandise-additional-fees",X:b.additionalFeesText})),c={F:"div",Z:["ytp-ce-element","ytp-ce-merchandise"],P:{tabindex:"0","aria-label":b.jl||"","aria-hidden":"true"},L:[{F:"div",I:"ytp-ce-element-shadow"},{F:"div",I:"ytp-ce-expanding-overlay",L:[{F:"div",I:"ytp-ce-expanding-overlay-hider"},{F:"div",I:"ytp-ce-expanding-overlay-background"},{F:"div",I:"ytp-ce-expanding-overlay-content",L:[{F:"div",
I:"ytp-ce-expanding-overlay-body",L:[{F:"div",I:"ytp-ce-expanding-overlay-body-padding",L:[{F:"div",I:"ytp-ce-merchandise-title",P:{dir:g.Mn(b.title||"")},X:b.title},c,{F:"div",I:"ytp-ce-merchandise-metadata",X:b.metadata},{F:"a",Z:["ytp-ce-merchandise-goto","ytp-ce-link"],P:{href:R2(a,b.targetUrl),target:"_blank",tabindex:"-1"},X:b.callToAction}]}]}]}]},{F:"div",I:"ytp-ce-expanding-image",P:Q2(b)},{F:"div",I:"ytp-ce-merchandise-invideo-cta-container",L:[{F:"div",I:"ytp-ce-merchandise-invideo-cta",
X:b.callToAction}]}]},c=new g.Q(c)}b.fG&&g.I(c.element,"ytp-ce-placeholder");return c},Q2=function(a){if(a.Vw)var b=a.Vw.thumbnails;
return Ssa(b?b[b.length-1].url:null)},Ssa=function(a){return a?{style:"background-image: url("+a+")"}:{}},Rsa=function(a,b,c){function d(){k(1)}
function e(){k(-1)}
b.ma("mouseenter",(0,g.w)(a.jt,a,b,c));b.ma("mouseleave",(0,g.w)(a.eu,a,b,c));a.player.O().o||b.ma("click",(0,g.w)(function(l){g.I(l.element,"ytp-ce-element-hover")},a,b));
b.ma("click",(0,g.w)(a.AA,a,c));b.ma("keypress",(0,g.w)(a.AA,a,c));b.ma("focus",(0,g.w)(function(l,m){this.jt(l,m)},a,b,c));
b.ma("blur",(0,g.w)(function(l,m){this.eu(l,m)},a,b,c));
b.ma("touchstart",(0,g.w)(a.jt,a,b,c));var f=g.ce("ytp-ce-expanding-overlay-hider",b.element);f&&b.M(f,"touchstart",function(l){l=l||window.event;l.cancelBubble=!0;l.stopPropagation&&l.stopPropagation();g.En(b.element,"ytp-ce-element-hover");g.En(b.element,"ytp-ce-force-expand")});
b.ma("keydown",(0,g.w)(function(l,m){this.N=9==m.keyCode&&!m.shiftKey},a,b));
var k=(0,g.w)(function(l,m,n){this.H+=n;0<this.H?(g.I(l.element,"ytp-ce-force-expand"),S2(this,m.id,!0)):(g.En(l.element,"ytp-ce-force-expand"),g.En(l.element,"ytp-ce-element-hover"),S2(this,m.id,!1))},a,b,c);
c=(0,g.w)(function(l,m){m&&(l.ma("blur",g.Qa(function(){"none"!=m.style.display&&a.N&&m.focus()})),l.M(m,"focus",d),l.M(m,"blur",e))},a,b);
c(g.ce("ytp-sb-subscribe",b.element));c(g.ce("ytp-sb-unsubscribe",b.element));b.ma("focus",d);b.ma("blur",e)},R2=function(a,b){var c=a.player.O();
if(b){if(b.startsWith("//"))return c.protocol+":"+b;if(b.startsWith("/"))return g.kz(c)+b}else return"";return b},S2=function(a,b,c){a.A&&(c?a.D.show():a.D.hide());
for(var d in a.o)d!=b&&g.J(a.o[d].element,"ytp-ce-element-shadow-show",c)},T2=function(a,b,c){function d(){f||(e++,e==b.length&&(k.stop(),c&&c()))}
if(!b||0==b.length||O2(a))c&&c();else{b=Tsa(a,b);var e=0,f=!1,k=new g.H(function(){f=!0;c&&c()},1E3,a);
k.start();for(a=0;a<b.length;a++)g.Rq(b[a],d)}},U2=function(a,b,c){T2(a,b.clickUrls,c);
(a=g.Sr())&&b.bG&&g.ms(a,b.visualElement)},Tsa=function(a,b){var c=a.player.getVideoData().clientPlaybackNonce,d=a.player.getCurrentTime().toFixed(2);
c={CPN:c,AD_CPN:c,MT:d};d=[];for(var e=0;e<b.length;e++)d.push(Usa(b[e],c));return d},Usa=function(a,b){return a.replace(/%5B[a-zA-Z_:]+%5D|\[[a-zA-Z_:]+\]/g,function(c){var d=unescape(c);
d=d.substring(1,d.length-1);return b[d]?escape(b[d]):c})},Vsa=function(a){return Array.isArray(a)&&a.length?a[0]:a},V2=function(a){return"string"===typeof a?a:""},W2=function(a,b,c){for(var d in b)if(b[d]==a)return a;
return c},Xsa=function(a){var b=Wsa;
if(null==a)return null;if(g.La(a)){var c=[];(0,g.x)(a,function(d){(d=b(d))&&c.push(d)});
return c}return(a=b(a))?[a]:[]},Ysa=function(a){this.externalId=a},Zsa=function(a,b,c,d){this.value=a;
this.target=b;this.showLinkIcon=c;this.o=d},X2=function(a){if(!a)return null;
var b=g.xc(V2(a.value));b=g.uc(b);if(!b)return null;var c=W2(a.target,$sa,"current");if(null==c)a=null;else{var d=a.show_link_icon;a=new Zsa(b,c,"true"==d||"false"==d?"true"==d:!0,null!=a.pause_on_navigation?a.pause_on_navigation:!0)}return a},Y2=function(a){return a.value?a.value:null},ata=function(a,b,c,d){this.type=a;
this.trigger=b;this.url=c;this.subscribeData=d},Wsa=function(a){if(!a)return null;
var b=W2(a.type,bta),c=W2(a.trigger,cta),d=Vsa(a.url);d=X2(d?d:null);a=Vsa(a.subscribeData);var e=a?a:null;e?(a=V2(e.external_user_id),e=V2(e.subscription_token),a=a&&e?new Ysa(a):null):a=null;return b?new ata(b,c,d,a):null},Z2=function(a,b,c,d,e){this.id=a;
this.type=b;this.style=c;this.o=d||[];this.data=e},dta=function(a,b){return g.Xa(a.o,b,void 0)},eta=function(a,b){return a.id.replace(/[^a-z0-9-]/gi,"-")+"-"+b.toString()},fta=function(a,b){this.merchant=a;
this.price=b},gta=function(a){this.o=a},hta=function(a,b,c){b&&(c?$2(a,(0,g.Dc)(b,g.Qa(function(d,e){return g.en(e,d)},c))):$2(a,b))},$2=function(a,b,c,d){var e=1,f=-1;
if(c){var k=!1;var l=function(){e--;e||k||(clearTimeout(f),k=!0,c())};
f=setTimeout(function(){k=!0;c()},1E3)}(0,g.x)(b||[],function(m){e++;
g.Rq(m,l)});
d&&(e++,0!=d&&a.o.sendVideoStatsEngageEvent(d,l))},ita=function(a,b,c,d,e,f,k){this.o=a;
this.A=b;this.B=c;this.videoData=d;this.logger=e;this.K=f;this.u=k},a3=function(a,b){this.o=a;
this.A=b},lta=function(a,b){var c=[];
(0,g.x)(b.choices,function(k){c.push(jta(b,k))},a);
var d={F:"ul",P:{role:"radiogroup"},L:c},e={};b.oj&&(e["aria-label"]=g.mM("$POLL_TITLE - Sign in to vote.",{POLL_TITLE:b.title}));var f=["iv-card","iv-card-poll"];d=[{F:"div",I:"iv-card-content",L:[b3("h2",e,b.title),{F:"form",L:[{F:"fieldset",L:[d]}]}]}];b.oj&&(f.push("iv-card-unavailable"),d.push({F:"div",Z:["iv-card-sign-in"],L:[{F:"h2",X:"Want to vote?"},{F:"a",Z:["iv-card-sign-in-button","iv-button"],P:{href:Y2(b.oj)},L:[{F:"span",Z:["iv-button-content"],X:"Sign in"}]}]}));f=new g.Q({F:"div",
Z:f,L:d});d=f.element;kta(b,d);Msa(a.o.o,d,g.Qa(a.B,b),a);(0,g.x)(g.be("iv-card-poll-choice-input",d),function(k){this.o.o.ma(k,"focus",g.Qa(this.u,!0));this.o.o.ma(k,"blur",g.Qa(this.u,!1))},a);
b.oj&&(d=g.ce("iv-card-sign-in-button",d),a.A(d,b.oj,b.id,b.Qb,b.Jc.click,5));return f},mta=function(a,b,c){var d=["yt-badge",
"standalone-ypc-badge-renderer-icon",b.PO?"standalone-ypc-badge-renderer-icon-purchased":"standalone-ypc-badge-renderer-icon-available"],e={};d=b.eG&&b.pw?{F:"span",Z:d,P:e,X:b.pw}:"";c={F:"div",Z:["iv-card",c],L:[{F:"a",I:"iv-click-target",P:{href:Y2(b.url)},L:[c3(b.sj,d?{F:"div",I:"iv-card-image-text",L:[d,b.priceText]}:""),{F:"div",I:"iv-card-content",L:[{F:"h2",I:"iv-card-primary-link",X:b.title},d3(a,b)]}]}]};c=new g.Q(c);e3(a,g.be("iv-click-target",c.element),b,b.url);return c},f3=function(a){return a.customMessage?
b3("div","iv-card-message",a.customMessage):""},c3=function(a,b){var c="background-image: url("+a+");",d=[];
b&&d.push(b);return{F:"div",I:"iv-card-image",P:{style:c},L:d}},d3=function(a,b){if(!b.metaInfo||0==b.metaInfo.length)return"";
var c=[];(0,g.x)(b.metaInfo,function(d){c.push(b3("li","",d))},a);
return{F:"ul",I:"iv-card-meta-info",L:c}},jta=function(a,b){return{F:"li",
I:eta(a,b.index),L:[{F:"label",L:[{F:"input",I:"iv-card-poll-choice-input",P:{type:"checkbox",role:"radio",name:a.id.replace(/[^a-z0-9-]/gi,"-")+b.index.toString(),value:b.index.toString(),"data-poll-choice-index":b.index.toString()}},{F:"span",I:"iv-card-poll-choice-text",L:[{F:"span",I:"iv-card-poll-choice-percent"},b3("span",void 0,b.desc)]}]},{F:"div",I:"iv-card-poll-result",L:[{F:"div",I:"iv-card-poll-result-bar"}]}]}},b3=function(a,b,c){b?"string"===typeof b?b={"class":b}:Array.isArray(b)&&
(b={"class":b.join(" ")}):b={};
b.dir=g.Mn(c);return{F:a,P:b,X:c}},nta=function(a){if(!a.customMessage)return"";
var b=["iv-card-action","iv-card-primary-link"],c={};a.zn&&(b.push("iv-card-action-icon"),c.style="background-image: url("+a.zn+");");c.dir=g.Mn(a.customMessage);var d=[{F:"span",X:a.customMessage}];a.showLinkIcon&&(d.push("\u00a0"),d.push({F:"span",I:"iv-card-link-icon"}));return{F:"div",Z:b,P:c,L:d}},kta=function(a,b){var c=0;
(0,g.x)(a.choices,function(m){c+=m.count});
c=c||1;for(var d=0;d<a.choices.length;d++){var e=a.choices[d],f=g.ce(eta(a,e.index),b);e=e.count/c;null==a.De&&(e=0);g.J(f.getElementsByTagName("label")[0],"iv-card-poll-choice-checked",a.De==d);f.getElementsByTagName("input")[0].checked=a.De==d;var k=Math.floor(100*e).toFixed(0),l=g.ce("iv-card-poll-choice-percent",f);g.ye(l,g.mM("$PERCENT%",{PERCENT:k}));f=g.ce("iv-card-poll-result-bar",f);g.th(f,"transform","scaleX("+e.toFixed(2)+")")}g.J(b,"iv-card-poll-voted",null!=a.De);g.J(b,"iv-card-poll-expanded",
null!=a.De&&1<a.choices.length)},e3=function(a,b,c,d){d&&(0,g.x)(b,function(e){this.A(e,d,c.id,c.Qb,c.Jc.click,5)},a)},ota=function(a){var b;
(b=a)&&!(b=1<a.length?"/"==a.charAt(0)&&"/"!=a.charAt(1):"/"==a)&&(b=a.replace(/^(https?:)?\/\//,""),b=b.split("/",1),b=!b||1>b.length||!b[0]?[]:b[0].toLowerCase().split(".").reverse(),b="com"==b[0]&&"youtube"==b[1]||"be"==b[0]&&"youtu"==b[1]);return b?-1==a.indexOf("/redirect?"):!1},pta=function(a,b){return b?b:ota(a)?"current":"new"},g3=function(a,b){g.z.call(this);
var c=this;this.Ha=a;this.context=b;this.jv=!1;this.fa=new Map;this.ka=new Map;this.context.K.addEventListener(g.bC("annotations_module"),function(d){(d=c.fa.get(d))&&d.apply(c)});
this.context.K.addEventListener("crx_annotations_module",function(d){(d=c.ka.get(d))&&d.apply(c)})},qta=function(a,b,c,d,e){var f=Y2(b);
if(f){var k=pta(f,b.target),l=(0,g.w)(function(){b.o&&this.context.K.pauseVideo();var m=this.context.videoData.oc||!1,n=g.bq(f||"");m&&n&&(n.v||n.list)?g.oT(this.context.K.app,n.v,c,n.list,!1,void 0):g.jO(f||"","current"==k?"_top":void 0,c)},a);
"new"==k&&(l(),l=null);$2(a.context.logger,d,l,e);ota(f)||(a=g.Sr(),d=c.itct,a&&d&&g.ms(a,g.Kr(d)))}},rta=function(a){if(a.urlEndpoint&&a.urlEndpoint.url)return a.urlEndpoint.url;
if(a.watchEndpoint&&a.watchEndpoint.videoId){var b="/watch?v="+a.watchEndpoint.videoId;a.watchEndpoint.playlistId&&(b+="&list="+a.watchEndpoint.playlistId);a.watchEndpoint.index&&(b+="&index="+a.watchEndpoint.index);a.watchEndpoint.startTimeSeconds&&(b+="&t="+a.watchEndpoint.startTimeSeconds);return b}return null},h3=function(a,b,c){return{iy:(a.impressionLoggingUrlsV2s||[]).map(function(d){return d.baseUrl}),
click:(c.loggingUrls||[]).map(function(d){return d.baseUrl}),
close:(b.dismissLoggingUrlsV2s||[]).map(function(d){return d.baseUrl}),
pC:(b.impressionLoggingUrlsV2s||[]).map(function(d){return d.baseUrl}),
oq:(b.clickLoggingUrlsV2s||[]).map(function(d){return d.baseUrl})}},k3=function(a,b,c){g3.call(this,b,c);
var d=this;this.u=a;this.ca=this.Fa=this.C=this.Da=!1;this.ga=null;this.ba=new g.H(g.Ia,c.B.gb?4E3:3E3);g.A(this,this.ba);this.wa=new g.H(g.Ia);g.A(this,this.wa);this.H=new a3(c,(0,g.w)(this.Mk,this),(0,g.w)(this.Mo,this));this.U=new g.Q({F:"div",I:"iv-drawer",P:{id:"iv-drawer"},L:[{F:"div",I:"iv-drawer-header",P:{"aria-role":"heading"},L:[{F:"span",I:"iv-drawer-header-text"},{F:"button",Z:["iv-drawer-close-button","ytp-button"],P:{"aria-label":"Hide cards",tabindex:"0"}}]},{F:"div",I:"iv-drawer-content"}]});
g.A(this,this.U);this.D=this.U.element;this.ra=new g.jN(this.U,330);g.A(this,this.ra);this.Aa=g.ce("iv-drawer-header-text",this.D);this.B=g.ce("iv-drawer-content",this.D);this.A=[];this.ya=this.S=this.G=this.ea=this.o=null;this.V=[];this.addCueRange(0,1E3*c.videoData.lengthSeconds,"",function(){d.Fa&&i3(d,"YOUTUBE_DRAWER_AUTO_OPEN")},function(){(d.Fa=d.C)&&j3(d)});
this.N=this.J=this.aa=null;this.R=0},sta=function(a,b){b.data.autoOpenMs&&a.addCueRange(b.data.autoOpenMs,0x8000000000000,"",function(){i3(a,"YOUTUBE_DRAWER_AUTO_OPEN")});
b.data.autoCloseMs&&a.addCueRange(b.data.autoCloseMs,0x8000000000000,"",function(){j3(a)});
var c=b.data.headerText;g.ye(a.Aa,c);a.S&&a.S.setAttribute("title",c);a.aa=g.Kr(b.data.trackingParams);a.N=g.Kr(b.data.closeTrackingParams);a.J=g.Kr(b.data.iconTrackingParams)},tta=function(a,b){var c=b.cardId?b.cardId:"cr:"+a.R;
if(b.content.simpleCardContentRenderer){if(!b.cueRanges.length)return;var d=b.content.simpleCardContentRenderer,e=b.teaser.simpleCardTeaserRenderer,f=b.icon?b.icon.infoCardIconRenderer:null;c={id:c,timestamp:a.R,type:"simple",teaserText:g.S(e.message),teaserDurationMs:parseInt(b.cueRanges[0].teaserDurationMs,10),startMs:parseInt(b.cueRanges[0].startCardActiveMs,10),autoOpen:!!b.autoOpen,Qb:l3(a,c,b,d),sponsored:!1,Jc:h3(d,e,d.command),de:d.trackingParams?g.Kr(d.trackingParams):null,Xd:e.trackingParams?
g.Kr(e.trackingParams):null,Ad:f&&f.trackingParams?g.Kr(f.trackingParams):null,imageUrl:m3(d.image.thumbnails,290).url,displayDomain:d.displayDomain?g.S(d.displayDomain):null,showLinkIcon:!!d.showLinkIcon,zn:null,title:d.title?g.S(d.title):"",customMessage:d.callToAction?g.S(d.callToAction):"",url:d.command.urlEndpoint.url?X2({pause_on_navigation:!a.context.videoData.za,target:"new",value:d.command.urlEndpoint.url}):null};n3(a,c)}else if(b.content.collaboratorInfoCardContentRenderer){if(!b.cueRanges.length)return;
d=b.content.collaboratorInfoCardContentRenderer;e=b.teaser.simpleCardTeaserRenderer;f=b.icon?b.icon.infoCardIconRenderer:null;c={id:c,timestamp:a.R,type:"collaborator",teaserText:g.S(e.message),teaserDurationMs:parseInt(b.cueRanges[0].teaserDurationMs,10),startMs:parseInt(b.cueRanges[0].startCardActiveMs,10),autoOpen:!!b.autoOpen,Qb:l3(a,c,b,d),sponsored:!1,Jc:h3(d,e,d.endpoint),de:d.trackingParams?g.Kr(d.trackingParams):null,Xd:e.trackingParams?g.Kr(e.trackingParams):null,Ad:f&&f.trackingParams?
g.Kr(f.trackingParams):null,channelId:d.endpoint.browseEndpoint.browseId,customMessage:d.customText?g.S(d.customText):null,xB:m3(d.channelAvatar.thumbnails,290).url,title:d.channelName?g.S(d.channelName):"",metaInfo:[d.subscriberCountText?g.S(d.subscriberCountText):""],url:X2({pause_on_navigation:!a.context.videoData.za,target:"new",value:d.endpoint.browseEndpoint.canonicalBaseUrl?d.endpoint.browseEndpoint.canonicalBaseUrl:"/channel/"+d.endpoint.browseEndpoint.browseId})};n3(a,c)}else if(b.content.playlistInfoCardContentRenderer){if(!b.cueRanges.length)return;
d=b.content.playlistInfoCardContentRenderer;e=b.teaser.simpleCardTeaserRenderer;f=b.icon?b.icon.infoCardIconRenderer:null;c={id:c,timestamp:a.R,type:"playlist",teaserText:g.S(e.message),teaserDurationMs:parseInt(b.cueRanges[0].teaserDurationMs,10),startMs:parseInt(b.cueRanges[0].startCardActiveMs,10),autoOpen:!!b.autoOpen,Qb:l3(a,c,b,d),sponsored:!1,Jc:h3(d,e,d.action),de:d.trackingParams?g.Kr(d.trackingParams):null,Xd:e.trackingParams?g.Kr(e.trackingParams):null,Ad:f&&f.trackingParams?g.Kr(f.trackingParams):
null,sj:m3(d.playlistThumbnail.thumbnails,258).url,customMessage:d.customMessage?g.S(d.customMessage):null,playlistVideoCount:g.S(d.playlistVideoCount),title:d.playlistTitle?g.S(d.playlistTitle):"",metaInfo:[d.channelName?g.S(d.channelName):"",d.videoCountText?g.S(d.videoCountText):""],url:X2({pause_on_navigation:!a.context.videoData.za,target:"new",value:rta(d.action)})};n3(a,c)}else if(b.content.videoInfoCardContentRenderer){if(!b.cueRanges.length)return;d=b.content.videoInfoCardContentRenderer;
e=b.teaser.simpleCardTeaserRenderer;f=b.icon?b.icon.infoCardIconRenderer:null;c={id:c,timestamp:a.R,type:"video",teaserText:g.S(e.message),teaserDurationMs:parseInt(b.cueRanges[0].teaserDurationMs,10),startMs:parseInt(b.cueRanges[0].startCardActiveMs,10),autoOpen:!!b.autoOpen,Qb:l3(a,c,b,d),sponsored:!1,Jc:h3(d,e,d.action),de:d.trackingParams?g.Kr(d.trackingParams):null,Xd:e.trackingParams?g.Kr(e.trackingParams):null,Ad:f&&f.trackingParams?g.Kr(f.trackingParams):null,sj:m3(d.videoThumbnail.thumbnails,
258).url,videoDuration:d.lengthString?g.S(d.lengthString):null,customMessage:d.customMessage?g.S(d.customMessage):null,title:d.videoTitle?g.S(d.videoTitle):"",metaInfo:[d.channelName?g.S(d.channelName):"",d.viewCountText?g.S(d.viewCountText):""],isLiveNow:!!d.badge,url:X2({pause_on_navigation:!a.context.videoData.za,target:"new",value:rta(d.action)})};n3(a,c)}a.R++},m3=function(a,b){for(var c=-1,d=-1,e=0;e<a.length;e++){if(a[e].height==b||290==a[e].width)return a[e];
((a[e].height||0)<b||290>(a[e].width||0))&&(0>c||(a[c].height||0)<(a[e].height||0)||(a[c].width||0)<(a[e].width||0))?c=e:((a[e].height||0)>=b||290<=(a[e].width||0))&&(0>d||(a[d].height||0)>(a[e].height||0)||(a[d].width||0)>(a[e].width||0))&&(d=e)}return a[0<=d?d:c]},l3=function(a,b,c,d){return{feature:c.feature?c.feature:"cards",
src_vid:a.context.videoData.videoId,annotation_id:b,ei:a.context.videoData.eventId,itct:d.trackingParams}},vta=function(a,b){var c=uta(a,b);
c&&(c==a.o&&(a.o=null),a.u.removeCueRange(c.card.id),g.te(c.mr),g.db(a.A,c),a.Cn(),o3(a))},i3=function(a,b,c){if(!a.C){a.ra.show();
a.ea=new g.H(function(){g.I(a.context.K.getRootNode(),g.rM.IV_DRAWER_OPEN)},0);
a.ea.start();a.ga=g.ep(a.B,"mousewheel",(0,g.w)(a.IL,a));a.C=!0;var d=g.Sr();d&&a.aa&&a.N&&B2(d,[a.aa,a.N]);var e={TRIGGER_TYPE:b};(0,g.x)(a.A,function(f){f.Jy||(f.Jy=!0,hta(a.context.logger,f.card.Jc.iy,e));d&&B2(d,[f.card.de])});
A2(a.u);c&&(a.G=new g.H(function(){a.va=a.S;a.ya.focus()},330),a.G.start())}},j3=function(a){a.C&&(a.ra.hide(),g.fp(a.ga),a.ga=null,g.En(a.context.K.getRootNode(),g.rM.IV_DRAWER_OPEN),a.C=!1,A2(a.u),a.G&&a.G.stop(),a.G=new g.H(function(){a.va&&(a.va.focus(),a.va=null)},330),a.G.start())},wta=function(a){var b=g.ce("iv-drawer-close-button",a.D);
a.context.o.ma(b,"click",a.mE,a);a.context.o.ma(a.B,"touchend",function(){a.ba.start()});
a.context.o.ma(a.B,"scroll",a.zE,a);a.context.u.subscribe("onHideControls",function(){a.ca=!0});
a.context.u.subscribe("onShowControls",function(){a.ca=!1});
a.context.u.subscribe("onVideoAreaChange",function(){a.ca=g.Cn(a.u.getRootNode(),"ytp-autohide")});
a.V.push(g.Po("iv-button-shown",a.lG,a));a.V.push(g.Po("iv-button-hidden",a.kG,a));a.V.push(g.Po("iv-teaser-shown",a.oG,a));a.V.push(g.Po("iv-teaser-hidden",a.nG,a));a.V.push(g.Po("iv-teaser-clicked",a.mG,a))},n3=function(a,b){a.Da||(g.Dn(a.xa(),[g.rM.STOP_EVENT_PROPAGATION,
"iv-drawer-manager"]),g.oL(a.u,a.D,5),wta(a),a.S=g.ce("ytp-cards-button",a.u.getRootNode()),a.ya=g.ce("iv-drawer-close-button",a.D),a.Da=!0);vta(a,b.id);var c=xta(a,b);if(c){var d={card:b,mr:c.element,Jy:!1},e=yta(a,d);g.kb(a.A,e,0,d);c.da(a.B,e);a.Cn();b.autoOpen?a.addCueRange(b.startMs,0x8000000000000,b.id,g.Qa(a.iO,d)):(c=1E3*a.context.K.getCurrentTime(),5E3>c&&c>b.startMs&&a.cC(d),a.addCueRange(b.startMs,b.startMs+1,b.id,g.Qa(a.cC,d)),o3(a))}},xta=function(a,b){switch(b.type){case "simple":var c=
a.H;
var d=b.displayDomain?{F:"div",I:"iv-card-image-text",X:b.displayDomain}:"";var e=nta(b);d={F:"div",Z:["iv-card"],L:[{F:"a",I:"iv-click-target",P:{href:Y2(b.url)},L:[c3(b.imageUrl,d),{F:"div",I:"iv-card-content",L:[b3("h2",void 0,b.title),e]}]}]};d=new g.Q(d);e3(c,g.be("iv-click-target",d.element),b,b.url);return d;case "collaborator":return c=a.H,d={F:"div",Z:["iv-card","iv-card-channel"],L:[{F:"a",Z:["iv-click-target"],P:{href:Y2(b.url),"data-ytid":b.channelId},L:[c3(b.xB),{F:"div",I:"iv-card-content",
L:[f3(b),{F:"h2",I:"iv-card-primary-link",X:b.title},d3(c,b)]}]}]},d=new g.Q(d),e3(c,g.be("iv-click-target",d.element),b,b.url),d;case "episode":return mta(a.H,b,"iv-card-episode");case "movie":return mta(a.H,b,"iv-card-movie");case "playlist":return c=a.H,d={F:"div",Z:["iv-card","iv-card-playlist"],L:[{F:"a",I:"iv-click-target",P:{href:Y2(b.url)},L:[c3(b.sj,{F:"div",I:"iv-card-image-overlay",L:[{F:"span",I:"iv-card-playlist-video-count",X:b.playlistVideoCount}]}),{F:"div",I:"iv-card-content",L:[f3(b),
b3("h2","iv-card-primary-link",b.title),d3(c,b)]}]}]},d=new g.Q(d),e3(c,g.be("iv-click-target",d.element),b,b.url),d;case "poll":return lta(a.H,b);case "productListing":c=a.H;var f=!g.ab(b.offers);d=["iv-card"];e="";var k=nta(b);f&&(d.push("iv-card-product-listing"),e="iv-card-primary-link",f=b.offers[0],k=[],f.price&&k.push({F:"div",I:"iv-card-offer-price",X:f.price}),f.merchant&&k.push({F:"div",I:"iv-card-offer-merchant",X:f.merchant}),k={F:"div",L:k});d={F:"div",Z:d,P:{tabindex:"0"},L:[{F:"a",
Z:["iv-card-image","iv-click-target"],P:{style:"background-image: url("+b.imageUrl+");",href:Y2(b.url),"aria-hidden":"true",tabindex:"-1"}},{F:"div",I:"iv-card-content",L:[b.sponsored?{F:"div",I:"iv-card-sponsored",L:["Sponsored",{F:"div",I:"iv-ad-info-container",L:[{F:"div",I:"iv-ad-info",X:"{{adInfo}}"},{F:"div",I:"iv-ad-info-icon-container",L:[{F:"div",I:"iv-ad-info-icon"},{F:"div",I:"iv-ad-info-callout"}]}]}]}:"",{F:"a",I:"iv-click-target",P:{href:Y2(b.url)},L:[b3("h2",e,b.title),k]}]}]};d=new g.Q(d);
e=g.oe("span");g.ye(e,"You are seeing this product because we think it is relevant to the video. Google may be compensated by the merchant.");d.rb(e,"adInfo");e3(c,g.be("iv-click-target",d.element),b,b.url);return d;case "video":return c=a.H,d=b.isLiveNow?{F:"span",Z:["yt-badge","yt-badge-live"],X:"LIVE NOW"}:"",d={F:"div",Z:["iv-card","iv-card-video"],L:[{F:"a",I:"iv-click-target",P:{href:Y2(b.url)},L:[c3(b.sj,b.videoDuration?{F:"span",I:"iv-card-video-duration",X:b.videoDuration}:""),{F:"div",I:"iv-card-content",
L:[f3(b),b3("h2","iv-card-primary-link",b.title),d3(c,b),d]}]}]},d=new g.Q(d),e3(c,g.be("iv-click-target",d.element),b,b.url),d}return null},yta=function(a,b){if(0==a.A.length)return 0;
var c=g.Ya(a.A,function(d){return b.card.startMs>d.card.startMs||b.card.startMs==d.card.startMs&&b.card.timestamp>=d.card.timestamp?!0:!1});
return-1==c?0:c+1},zta=function(a){return a.o?"productListing"==a.o.card.type:(0,g.ui)(a.A,function(b){return"productListing"==b.card.type})},o3=function(a){g.J(a.u.getRootNode(),"ytp-cards-shopping-active",zta(a))},Ata=function(a,b){if(a.U.Ka()){var c=new G2([0,
a.B.scrollTop],[0,b.mr.offsetTop],600,Gsa);a.context.A.ma(c,"animate",function(d){a.B.scrollTop=d.y});
a.context.A.ma(c,"finish",function(d){a.B.scrollTop=d.y});
c.play()}else g.Fu(a.U,!0),a.B.scrollTop=b.mr.offsetTop,g.Fu(a.U,!1)},p3=function(a){return a.o&&a.o.card?a.o.card:a.A[0]&&a.A[0].card?a.A[0].card:null},uta=function(a,b){return g.Xa(a.A,function(c){return c.card.id==b})},q3=function(a,b,c){g3.call(this,a,b);
this.annotation=c;this.isActive=!1},Bta=function(a){var b=a.annotation.data;
"start_ms"in b&&"end_ms"in b&&a.addCueRange(a.annotation.data.start_ms,a.annotation.data.end_ms,a.annotation.id,function(){a.show()},function(){a.hide()})},r3=function(a,b,c){q3.call(this,a,b,c);
this.u=null;this.G=!1;this.A=null;this.B=!1;this.o=this.D=this.C=null},s3=function(a,b,c){q3.call(this,a,b,c);
this.J=this.C=this.R=!1;this.G=5E3;this.B=null;this.H=g.ne("DIV","iv-promo-contents");this.u=this.A=this.o=null;this.D=new g.H(function(){this.o.setAttribute("aria-hidden",!0);g.Nh(this.A,!1);g.Nh(this.u,!0)},700,this);
g.A(this,this.D)},Cta=function(a){var b=a.annotation.data;
if("cta"==a.annotation.style)var c=6;else if("video"==a.annotation.style||"playlist"==a.annotation.style)c=7;a.G=b.collapse_delay_ms||a.G;var d=["iv-promo","iv-promo-inactive"];a.xa().setAttribute("aria-hidden",!0);a.xa().setAttribute("aria-label","Promotion");a.xa().tabIndex=0;var e=a.annotation.kc(),f=b.image_url;if(f){var k=g.ne("DIV",["iv-promo-img","iv-click-target"]);f=g.ne("IMG",{src:f,"aria-hidden":"true"});k.appendChild(f);b.video_duration&&!b.is_live?(f=g.ne("SPAN","iv-promo-video-duration",
b.video_duration),k.appendChild(f)):b.playlist_length&&(f=g.ne("SPAN","iv-promo-playlist-length",b.playlist_length.toString()),k.appendChild(f));e&&a.Mk(k,e,a.annotation.id,b.session_data,void 0,c)}e?(f=g.ne("A","iv-promo-txt"),g.Yc(f,Y2(e)),a.o=f):a.o=g.ne("DIV","iv-promo-txt");switch(a.annotation.style){case "cta":case "website":var l=g.ne("P",null,g.ne("STRONG",null,b.text_line_1));var m=g.ne("P",null,g.ne("SPAN","iv-promo-link",b.text_line_2));if(f=b.text_line_3){d.push("iv-promo-website-card-cta-redesign");
g.O(a.context.B.experiments,"web_action_cta_larger_ui")&&d.push("iv-promo-website-card-cta-larger-ui");var n=g.ne("BUTTON",["iv-promo-round-expand-icon","ytp-button"]);f=g.ne("BUTTON",["iv-button","iv-promo-button"],g.ne("SPAN","iv-button-content",f));var q=g.ne("DIV","iv-promo-button-container");q.appendChild(f);e&&a.Mk(a.xa(),e,a.annotation.id,b.session_data,void 0,c)}g.I(a.o,"iv-click-target");e&&a.Mk(a.o,e,a.annotation.id,b.session_data,void 0,c);break;case "playlist":case "video":l=g.ne("P",
null,g.ne("SPAN",null,b.text_line_1)),m=g.ne("P",null,g.ne("STRONG",null,b.text_line_2)),b.is_live&&(l=m,m=g.ne("SPAN",["yt-badge","iv-promo-badge-live"],"LIVE NOW")),g.I(a.o,"iv-click-target"),e&&a.Mk(a.o,e,a.annotation.id,b.session_data,void 0,c),d.push("iv-promo-video")}l&&a.o.appendChild(l);m&&a.o.appendChild(m);a.H.appendChild(a.o);q&&a.H.appendChild(q);c=g.ne("DIV","iv-promo-actions");a.u=g.ne("BUTTON",["iv-promo-expand","ytp-button"]);a.u.title="Expand";a.context.o.ma(a.u,"click",g.Qa(a.ws,
5E3),a);c.appendChild(a.u);g.Nh(a.u,!1);a.context.o.ma(a.xa(),"mouseover",a.wF,a);a.context.o.ma(a.xa(),"mouseout",a.vF,a);a.context.o.ma(a.xa(),"touchend",g.Qa(a.ws,5E3),a);a.A=g.ne("BUTTON",["iv-promo-close","ytp-button"]);a.A.title="Close";a.context.o.ma(a.A,"click","cta"==a.annotation.style&&b.text_line_3?a.oF:a.nF,a);c.appendChild(a.A);g.Dn(a.xa(),d);k&&(a.xa().appendChild(k),n&&k.appendChild(n));a.xa().appendChild(a.H);a.xa().appendChild(c)},Dta=function(a){a.C||a.J||a.B||(g.I(a.xa(),"iv-promo-collapsed"),
a.C=!0,a.D.start())},Eta=function(a){a.D.stop();
a.C&&(g.Fn(a.xa(),["iv-promo-collapsed","iv-promo-collapsed-no-delay"]),a.C=!1,a.o&&a.o.removeAttribute("aria-hidden"),g.Nh(a.u,!1),g.Nh(a.A,!0))},Fta=function(a,b){a.B||(a.B=g.Uf(function(){t3(this);
Dta(this)},b,a))},t3=function(a){a.B&&(g.v.clearTimeout(a.B),a.B=null)},u3=function(a){g.BL.call(this,a);
this.R=!1;this.J=0;this.G={};this.V=new gta(a);this.C=new g.ur(this);g.A(this,this.C);this.D=this.A=null;this.C.M(this.player,"onVideoAreaChange",(0,g.w)(this.T,this,"onVideoAreaChange"));this.C.M(this.player,"onHideControls",(0,g.w)(this.T,this,"onHideControls"));this.C.M(this.player,"onShowControls",(0,g.w)(this.T,this,"onShowControls"));this.C.M(this.player,"resize",(0,g.w)(this.T,this,"resize"));this.C.M(this.player,"presentingplayerstatechange",(0,g.w)(this.T,this,"presentingplayerstatechange"));
this.subscribe("presentingplayerstatechange",this.dM,this);this.subscribe("resize",this.Ip,this);this.player.O().J.subscribe("vast_info_card_add",this.jB,this);this.U=new g.ur(this);g.A(this,this.U);this.S=g.ne("DIV","video-custom-annotations");this.u=new g.Q({F:"div",Z:["ytp-player-content","ytp-iv-player-content"]});g.A(this,this.u);g.oL(this.player,this.u.element,4);this.u.hide();this.B=new g.Q({F:"div",Z:["ytp-iv-video-content"]});g.A(this,this.B);g.qe(this.B.element,g.ne("DIV","video-annotations",
this.S));this.H=this.o=null;this.N=[];Gta(this)&&this.load();var b=g.oe("STYLE");(document.getElementsByTagName("HEAD")[0]||document.body).appendChild(b);g.Ge(this,function(){g.te(b)});
if(a=b.sheet)a.insertRule(".iv-promo .iv-promo-contents .iv-promo-txt .iv-promo-link:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABQAAAAUBAMAAAB/pwA+AAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAHlBMVEVMaXH////////////////////////////////////Z6AnKAAAACXRSTlMA+/A2IuI1mJIldm0CAAAAAWJLR0QB/wIt3gAAAEVJREFUCNdjYGCYCQUMBJlACOIzIDElIcyZkwxgojOVWWDMSQauMKYySySUOSnBdSaUOZ0lEsac2YqwYiZ+JhwgM7E5HACgzVCI/YJ59AAAAABJRU5ErkJggg==) no-repeat center;background-size:10px;width:10px;height:10px}",
0),a.insertRule(".iv-promo .iv-promo-actions .iv-promo-close:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAkAAAAJBAMAAAASvxsjAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXH///////////////////////////////////////////9tKdXLAAAAC3RSTlMAVaQDpaimqQbl5rjXUFUAAAABYktHRAH/Ai3eAAAAPUlEQVQI12MQMmAwEmDwDmaOTmAw39663YCBuXp2MQMDQ+fOBgYG5ujVwQwMptvbgeLaxczVCQwiBgxmAgBkXg1FN5iwiAAAAABJRU5ErkJggg==) no-repeat center;background-size:9px;width:9px;height:9px}",
0),a.insertRule(".iv-promo .iv-promo-actions .iv-promo-expand:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAQAAAAJBAMAAADnQZCTAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXHMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMz////eMKB4AAAAC3RSTlMAOpE7k5Uvj5kpfRaQSaQAAAABYktHRAsf18TAAAAAHklEQVQI12MQYGBQZmBwTWCo0GSo6AKRQDZQRIABADXXA/UkIpvtAAAAAElFTkSuQmCC) no-repeat center;background-size:4px 9px;width:4px;height:9px}",0),a.insertRule(".iv-promo-website-card-cta-redesign .iv-promo-round-expand-icon:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAADAAAAAwCAQAAAD9CzEMAAAAAmJLR0QA/4ePzL8AAAAJcEhZcwAACxMAAAsTAQCanBgAAAAHdElNRQfgCgUUEztsNfqrAAAAXklEQVRYw+3Uuw2AQAwEUUNXfBpDIvBRMhQwJJAScNrA0r4CdiQHjjAzK4NGKucPAFmCnZcmwcTphBNO9CTGH4VB+/Zm6YlYis9fhedXz38FNvFriCCl808iw8ysrBu65gCeuV/CfgAAAABJRU5ErkJggg==) no-repeat center;background-size:18px 18px;width:18px;height:18px}",
0),a.insertRule(".iv-card-link-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASBAMAAACk4JNkAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAGFBMVEVMaXG7u7u7u7u7u7u7u7u7u7u7u7v///+WKTAlAAAABnRSTlMAFdQWbGj9GiOuAAAAAWJLR0QHFmGI6wAAAEhJREFUCNdjYACBNCBgQGMxMKrBWEJJaRAJRjVlKEsoSQDIAqtSZICwgEIQFkgIZBRECMxiBqsCsVjAqsCygQwwFgMeFgQgswBg2xjLrfC4mgAAAABJRU5ErkJggg==) no-repeat center;background-size:9px;width:9px;height:9px}",0),a.insertRule(".iv-card-playlist-video-count:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYBAMAAAASWSDLAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXH///////////////////////////////////////////9tKdXLAAAAC3RSTlMAvDeyLvxYtDK9Ogx4T1QAAAABYktHRAH/Ai3eAAAAK0lEQVQY02NgoBjshgO8HJoYwKiAMGAD92YHJM7uMCTO9gaEHs4FlPuZAQC8Fj8x/xHjxwAAAABJRU5ErkJggg==) no-repeat center;background-size:24px;width:24px;height:24px}",
0),a.insertRule(".iv-drawer-close-button:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAwAAAAMAgMAAAArG7R0AAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAACVBMVEVMaXH////////OZTV/AAAAAnRSTlMAoKBFbtAAAAABYktHRAH/Ai3eAAAAKUlEQVQI12MIYGBlSGGQBMIUBjbHCQyM0xwYGDIZwBjEBomB5EBqgGoBolQGzYuy51cAAAAASUVORK5CYII=) no-repeat center;background-size:12px;width:12px;height:12px}",0),a.insertRule(".iv-ad-info-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAsAAAALCAMAAACecocUAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAVFBMVEVMaXGUlJSYmJiZmZmYmJiXl5eZmZmZmZmWlpaVlZWOjo6ZmZmSkpKXl5eYmJiYmJiZmZmZmZmZmZmZmZmYmJiJiYmXl5eZmZmYmJiWlpaZmZn///+81lbeAAAAGnRSTlMAE5DM80DliTMMEjccWIM5p1UjaTQNgB5cLlr5mgUAAAABYktHRBsCYNSkAAAAVElEQVQI102NRw7AIBADhw7ppIf/PzQLJ/ZgWSNrFlDaWKMVcs6HmGLwTqjEME6CFDrAXBYIGhNh3TJEg02wHydctvFc7sbrvnXZV8/zfs3T+7u/P7CrAso35YfPAAAAAElFTkSuQmCC) no-repeat center;background-size:11px;width:11px;height:11px}",
0),a.insertRule(".annotation-close-button {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQBAMAAADt3eJSAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAALVBMVEVMaXEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/Pz9aWloBAQGZmZlbW1v///+X9wUzAAAACHRSTlMANprf+g6lyRmB9hUAAAABYktHRA5vvTBPAAAAWUlEQVQI12NgYBAycVZkAIKwDiBIZWBgrQAx2gMY2DrAIIFBomPWju6VHY0MGh1rbu891dHEYNGx9+yd2x3NDB4d3XfO7uhoQTDgUnDFcO1wA+FWwC2FOQMAdKg6tUSAFEAAAAAASUVORK5CYII=) no-repeat center}",0),a.insertRule(".annotation-link-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACIAAAAiCAMAAAANmfvwAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAUVBMVEVMaXH////////////////////////////////////////////////////////////////////////////////////////////////////////JzkR1AAAAGnRSTlMAfXf+c3xsdGdv/GJoXPtXXflSVk5L7DBH9VeFfsQAAAABYktHRAH/Ai3eAAAAgElEQVQ4y93SSQ6AIAwFULSOOOJs739Qf9SF0VA2uNCu+psHaQJK7cVCqY+Rg92PXA++Q84KnCR03UIRJrFEKMEgZYFQhpyzQHSBWJJAdIVUENtJ3SC0mu3EdOh7zXZiBrRdzQLJ0Y1GfOlpVstD3HaZktX9X/gvRCxvxL6FR7IBS1RTM5xIpLoAAAAASUVORK5CYII=) no-repeat center}",
0)},Hta=function(){var a=g.ne("DIV",["annotation",
"annotation-type-custom"]);g.Nh(a,!1);return a},Ita=function(a){switch(a){case "annotation-editor":case "live-dashboard":return!0}return!1},Gta=function(a){var b=a.player.O();
a=a.player.getVideoData();return 1==(b.annotationsLoadPolicy||a.annotationsLoadPolicy)&&!a.SC||b.J.get(a.videoId)||g.BB(a)||g.CB(a)?!0:!1},Jta=function(a,b){var c=!b.isCued()&&!g.U(b,1024);
g.Fu(a.u,c);g.Fu(a.B,c)},Kta=function(a,b,c){a.R=!0;
a.D=g.tq(b,c)},Lta=function(a,b){for(var c={},d=0;d<b.attributes.length;d++){var e=b.attributes[d];
c[e.name]=e.nodeValue}for(d=0;d<b.childNodes.length;d++)if(e=b.childNodes[d],g.Na(e)&&1==e.nodeType){if(c[e.tagName])var f=c[e.tagName];else if("data"==e.tagName){0<e.childNodes.length&&(f=e.childNodes[0].nodeValue,c[e.tagName]="string"==typeof f?f.trim():f);continue}else f=[],c[e.tagName]=f;e&&"TEXT"==e.tagName?1==e.childNodes.length&&3==e.childNodes[0].nodeType?f.push(e.childNodes[0].nodeValue):f.push(""):e&&f.push(Lta(a,e))}return c},Mta=function(a,b,c){return!(a.loaded&&a.J==b&&a.player.getVideoData().videoId==
c)},Pta=function(a){var b=a.player.getVideoData();
if(b.be){var c=a.player.O().J.get(b.videoId);if(c){var d={format:"XML",Yd:{},method:"POST",withCredentials:!0};d.Ic=(0,g.w)(function(e,f,k){Mta(this,e,f)||(e=g.nq(k)&&k.responseXML?k.responseXML:null)&&v3(this,e)},a,a.J,b.videoId);
g.vp()&&(d.Ic=Nta(a,d.Ic));d.tb={ic_only:"1"};Ota(d,c);a.R=!0;g.tq(b.be,d)}}},Ota=function(a,b){a.method="POST";
a.tb=a.tb||{};b.Gn&&(a.tb.ic_coll=b.Gn);b.Hn&&(a.tb.ic_xml=b.Hn);b.Xm&&(a.tb.ic_track=b.Xm)},Qta=function(a){var b=new g.Q({F:"div"});
g.Nh(b.element,!1);var c=new k3(a.player,b.element,w3(a));g.A(c,b);b.da(a.u.element);c.Mm();return c},w3=function(a){if(!a.H){var b=new J2(a);
g.A(a,b);var c=new g.A1(a);g.A(a,c);a.H=new ita(b,c,a.player.O(),a.player.getVideoData(),a.V,a.player,a.Uh)}return a.H},v3=function(a,b){var c=!1,d=b.getElementsByTagName("annotations");
if(d&&!(1>d.length)&&(d=d[0].getAttribute("itct"))){var e=g.Sr();if(e){var f=g.Qr();f&&g.gs(g.yo("use_default_events_client")?void 0:g.Fq,e,f,[g.Kr(d)])}}d=b.getElementsByTagName("annotation");for(e=0;e<d.length;e++){var k=Lta(a,d[e]);f=null;try{if(k){var l=k.id,m=/.+/;var n="string"===typeof l&&null!=m&&null!=l&&l.match(m)?l:"";var q=W2(k.type,Rta),t=W2(k.style,Sta),u=V2(k.data),y=0!=u.length?JSON.parse(u):{},C=Xsa(k.action);f=n&&q?new Z2(n,q,t,C,y):null}else f=null}catch(ha){}if(f){a:{switch(f.type){case "branding":case "promotion":k=
!0;break a}k=!1}if(k){k=a;m=f;var D=Hta(),E=null;switch(m.type){case "branding":if(k.player.O().Aa)break;k.u.element.appendChild(D);E=new r3(D,w3(k),m);break;case "promotion":g.oL(k.player,D,4),E=new s3(D,w3(k),m)}E&&E.Mm();if(k=E)g.A(a,k),a.G[f.id]=k}else if("card"==f.type||"drawer"==f.type){a.o||(a.o=Qta(a),g.A(a,a.o));if("card"==f.type){if(c=a.o,E=f&&f.data&&f.data.card_type)switch(k=f.data.tracking||{},k={iy:k.impression,click:k.click,close:k.close,pC:k.teaser_impression,oq:k.teaser_click},m=
f.data.tracking_params||{},D=null,E){case "collaborator":f={id:f.id,timestamp:f.data.timestamp||0,type:f.data.card_type,teaserText:f.data.teaser_text,teaserDurationMs:f.data.teaser_duration_ms,startMs:f.data.start_ms,autoOpen:f.data.auto_open||!1,Qb:f.data.session_data||{},sponsored:f.data.sponsored||!1,Jc:k,de:m.card?g.Kr(m.card):null,Xd:m.teaser?g.Kr(m.teaser):null,Ad:m.icon?g.Kr(m.icon):null,channelId:f.data.channel_id,customMessage:f.data.custom_message?f.data.custom_message:null,xB:f.data.image_url,
title:f.data.title,metaInfo:f.data.meta_info,url:X2({pause_on_navigation:f.data.pause_on_navigation,target:f.data.target||"new",value:f.data.url})};n3(c,f);break;case "episode":case "movie":f={id:f.id,timestamp:f.data.timestamp||0,type:f.data.card_type,teaserText:f.data.teaser_text,teaserDurationMs:f.data.teaser_duration_ms,startMs:f.data.start_ms,autoOpen:f.data.auto_open||!1,Qb:f.data.session_data||{},sponsored:f.data.sponsored||!1,Jc:k,de:m.card?g.Kr(m.card):null,Xd:m.teaser?g.Kr(m.teaser):null,
Ad:m.icon?g.Kr(m.icon):null,sj:f.data.image_url,pw:f.data.badge_symbol||"",priceText:f.data.price_text||"",title:f.data.title,metaInfo:f.data.meta_info,eG:!!f.data.is_paygated,PO:!!f.data.user_has_entitlement,url:X2({target:f.data.target||"new",value:f.data.url})};n3(c,f);break;case "playlist":f={id:f.id,timestamp:f.data.timestamp||0,type:f.data.card_type,teaserText:f.data.teaser_text,teaserDurationMs:f.data.teaser_duration_ms,startMs:f.data.start_ms,autoOpen:f.data.auto_open||!1,Qb:f.data.session_data||
{},sponsored:f.data.sponsored||!1,Jc:k,de:m.card?g.Kr(m.card):null,Xd:m.teaser?g.Kr(m.teaser):null,Ad:m.icon?g.Kr(m.icon):null,sj:f.data.image_url,playlistVideoCount:f.data.playlist_video_count,customMessage:f.data.custom_message?f.data.custom_message:null,title:f.data.title,metaInfo:f.data.meta_info,url:X2({pause_on_navigation:f.data.pause_on_navigation,target:f.data.target||"new",value:f.data.url})};n3(c,f);break;case "poll":f={id:f.id,timestamp:f.data.timestamp||0,type:f.data.card_type,teaserText:f.data.teaser_text,
teaserDurationMs:f.data.teaser_duration_ms,startMs:f.data.start_ms,autoOpen:f.data.auto_open||!1,Qb:f.data.session_data||{},sponsored:f.data.sponsored||!1,Jc:k,de:m.card?g.Kr(m.card):null,Xd:m.teaser?g.Kr(m.teaser):null,Ad:m.icon?g.Kr(m.icon):null,title:f.data.title,choices:f.data.choices,De:f.data.hasOwnProperty("old_vote")?f.data.old_vote:null,oj:f.data.signin_url?X2({target:"current",value:f.data.signin_url}):null,aP:f.data.hasOwnProperty("xsrf_token")?f.data.xsrf_token:null};n3(c,f);break;case "productListing":f.data.signin_url&&
(D=X2({target:"current",value:f.data.signin_url}));E=[];for(var F=f.data.offers||[],G=0;G<F.length;G++)E.push(new fta(g.fd(F[G].merchant),g.fd(F[G].price)));f={pT:!1,id:f.id,timestamp:f.data.timestamp||0,type:f.data.card_type,teaserText:f.data.teaser_text,teaserDurationMs:f.data.teaser_duration_ms,startMs:f.data.start_ms,autoOpen:f.data.auto_open||!1,Qb:f.data.session_data||{},sponsored:f.data.sponsored||!1,Jc:k,de:m.card?g.Kr(m.card):null,Xd:m.teaser?g.Kr(m.teaser):null,Ad:m.icon?g.Kr(m.icon):null,
imageUrl:f.data.image_url,displayDomain:f.data.display_domain?f.data.display_domain:null,showLinkIcon:!!f.data.show_link_icon,zn:f.data.button_icon_url?f.data.button_icon_url:null,title:f.data.title,customMessage:f.data.custom_message?f.data.custom_message:null,url:X2({pause_on_navigation:f.data.pause_on_navigation,target:f.data.target||"new",value:f.data.url}),oj:D,LT:f.data.signin_title?f.data.signin_title:null,KT:f.data.signin_message?f.data.signin_message:null,offers:E};n3(c,f);break;case "simple":f=
{id:f.id,timestamp:f.data.timestamp||0,type:f.data.card_type,teaserText:f.data.teaser_text,teaserDurationMs:f.data.teaser_duration_ms,startMs:f.data.start_ms,autoOpen:f.data.auto_open||!1,Qb:f.data.session_data||{},sponsored:f.data.sponsored||!1,Jc:k,de:m.card?g.Kr(m.card):null,Xd:m.teaser?g.Kr(m.teaser):null,Ad:m.icon?g.Kr(m.icon):null,imageUrl:f.data.image_url,displayDomain:f.data.display_domain?f.data.display_domain:null,showLinkIcon:!!f.data.show_link_icon,zn:f.data.button_icon_url?f.data.button_icon_url:
null,title:f.data.title,customMessage:f.data.custom_message?f.data.custom_message:null,url:X2({pause_on_navigation:f.data.pause_on_navigation,target:f.data.target||"new",value:f.data.url})};n3(c,f);break;case "video":f={id:f.id,timestamp:f.data.timestamp||0,type:f.data.card_type,teaserText:f.data.teaser_text,teaserDurationMs:f.data.teaser_duration_ms,startMs:f.data.start_ms,autoOpen:f.data.auto_open||!1,Qb:f.data.session_data||{},sponsored:f.data.sponsored||!1,Jc:k,de:m.card?g.Kr(m.card):null,Xd:m.teaser?
g.Kr(m.teaser):null,Ad:m.icon?g.Kr(m.icon):null,sj:f.data.image_url,videoDuration:f.data.video_duration||null,customMessage:f.data.custom_message?f.data.custom_message:null,title:f.data.title,metaInfo:f.data.meta_info,isLiveNow:!!f.data.is_live_now,url:X2({pause_on_navigation:f.data.pause_on_navigation,target:f.data.target||"new",value:f.data.url})},n3(c,f)}}else sta(a.o,f);c=!0}}}c&&(A2(a.player),a.Ip())},Tta=function(a,b){var c=!1;
a.o||(a.o=Qta(a),g.A(a,a.o));for(var d=g.p(b.cards||[]),e=d.next();!e.done;e=d.next())tta(a.o,e.value.cardRenderer),c=!0;c&&(c=a.o,d=b.headerText?g.S(b.headerText):"",g.ye(c.Aa,d),c.S&&c.S.setAttribute("title",d),c.aa=b.trackingParams?g.Kr(b.trackingParams):null,c.N=b.closeButton.infoCardIconRenderer.trackingParams?g.Kr(b.closeButton.infoCardIconRenderer.trackingParams):null,c.J=b.icon.infoCardIconRenderer.trackingParams?g.Kr(b.icon.infoCardIconRenderer.trackingParams):null,A2(a.player),a.Ip())},
Uta=function(a,b,c,d,e){if(!a.player.O().Aa){var f=[];
b.navigationEndpoint&&b.navigationEndpoint.browseEndpoint&&b.navigationEndpoint.browseEndpoint.browseId&&f.push(new ata("openUrl","click",new Zsa("/channel/"+b.navigationEndpoint.browseEndpoint.browseId,"new",!0,!0),null));var k=b.watermark.thumbnails[0];d={channel_name:b.channelName,end_ms:b.endTimeMs,image_height:k.height,image_type:1,image_url:k.url,image_width:k.width,is_mobile:!1,session_data:{annotation_id:c,ei:e,feature:"iv",itct:b.trackingParams,src_vid:d},start_ms:b.startTimeMs};if(b.subscribeButton&&
b.subscribeButton.subscribeButtonRenderer){d.channel_id=b.subscribeButton.subscribeButtonRenderer.channelId;b=b.subscribeButton.subscribeButtonRenderer;k=e=null;b.subscribed?(b.subscriberCountWithUnsubscribeText&&(e=g.S(b.subscriberCountWithUnsubscribeText)),b.subscriberCountText&&(k=g.S(b.subscriberCountText))):(b.subscriberCountText&&(e=g.S(b.subscriberCountText)),b.subscriberCountWithSubscribeText&&(k=g.S(b.subscriberCountWithSubscribeText)));var l="";b.signInEndpoint&&b.signInEndpoint.webNavigationEndpointData&&
b.signInEndpoint.webNavigationEndpointData.url&&(l=b.signInEndpoint.webNavigationEndpointData.url);b={subscribeText:g.S(b.unsubscribedButtonText),subscribeCount:e,unsubscribeText:g.S(b.subscribedButtonText),unsubscribeCount:k,enabled:b.enabled,classic:!1,subscribed:b.subscribed,feature:"iv",signInUrl:l};d.standalone_subscribe_button_data=b}f=new Z2(c,"branding","branding",f,d);d=Hta();a.u.element.appendChild(d);f=new r3(d,w3(a),f);f.Mm();g.A(f,f);a.G[c]=f}},Nta=function(a,b){return(0,g.w)(function(){if(!this.ha()){var c=
Array.prototype.slice.call(arguments,0);
c.unshift(b);b=g.Qa.apply(window,c);this.N.push(g.tp(b))}},a)},D2={},E2=null;g.Sa(G2,g.Gn);g.h=G2.prototype;g.h.getDuration=function(){return this.duration};
g.h.play=function(a){if(a||0==this.o)this.progress=0,this.coords=this.A;else if(this.fb())return!1;F2(this);this.startTime=a=(0,g.B)();-1==this.o&&(this.startTime-=this.duration*this.progress);this.endTime=this.startTime+this.duration;this.C=this.startTime;this.progress||this.Fp();this.se("play");-1==this.o&&this.se("resume");this.o=1;var b=g.Pa(this);b in D2||(D2[b]=this);Isa();Jsa(this,a);return!0};
g.h.stop=function(a){F2(this);this.o=0;a&&(this.progress=1);Ksa(this,this.progress);this.se("stop");this.zm()};
g.h.pause=function(){this.fb()&&(F2(this),this.o=-1,this.se("pause"))};
g.h.Y=function(){0==this.o||this.stop(!1);this.se("destroy");G2.Gb.Y.call(this)};
g.h.destroy=function(){this.dispose()};
g.h.Yt=function(){this.se("animate")};
g.h.se=function(a){this.dispatchEvent(new Lsa(a,this))};
g.Sa(Lsa,g.Je);g.Sa(H2,G2);H2.prototype.B=g.Ia;H2.prototype.Yt=function(){this.B();H2.Gb.Yt.call(this)};
H2.prototype.zm=function(){this.B();H2.Gb.zm.call(this)};
H2.prototype.Fp=function(){this.B();H2.Gb.Fp.call(this)};
g.Sa(I2,H2);I2.prototype.B=function(){this.element.style.left=Math.round(this.coords[0])+"px";this.element.style.top=Math.round(this.coords[1])+"px"};g.r(J2,g.z);J2.prototype.ma=function(a,b,c,d){c=(0,g.w)(c,d||this.u);a=g.ep(a,b,c);this.o.push(a);return a};
J2.prototype.Ts=function(a,b,c,d){c=(0,g.w)(c,d||this.u);a=g.op(a,b,c);this.o.push(a);return a};
J2.prototype.eb=function(a){g.fp(a);g.db(this.o,a)};
J2.prototype.Y=function(){g.fp(this.o);this.o.length=0;g.z.prototype.Y.call(this)};g.r(N2,g.BL);g.h=N2.prototype;g.h.load=function(){g.BL.prototype.load.call(this);if(!O2(this)){var a=g.AB(this.player.getVideoData());if(a)a=M2(a,Osa(this)),P2(this,a,!1);else{var b=this.player.getVideoData();a=b.videoId;this.B&&this.B.abort();a={method:"POST",Ic:(0,g.w)(this.RK,this,a),Yd:{v:a},withCredentials:!0};this.R&&(a.Yd.ptype="embedded");var c=this.player.getVideoData().Sn;c&&(a.tb={ad_tracking:c});if(b=g.zB(b))if(b=g.xc(b),b=g.uc(b))this.B=g.tq(b,a)}}};
g.h.unload=function(){P2(this,null);this.B&&(this.B.abort(),this.B=null);g.BL.prototype.unload.call(this)};
g.h.Rc=function(a,b){if(!O2(this))return null;if("loadCustomEndscreenRenderer"==a){var c=M2(b,"new");P2(this,c);return!0}return null};
g.h.getOptions=function(){return O2(this)?["loadCustomEndscreenRenderer"]:[]};
g.h.RK=function(a,b){var c=this.B=null;if(200==b.status){var d=b.responseText;")]}"==d.substring(0,3)&&(d=d.substring(3),c=JSON.parse(d),c=M2(c,Osa(this)))}P2(this,c)};
g.h.dz=function(){if(this.u&&this.u.elements){var a=this.player.getVideoContentRect();if(a&&0!=a.width&&0!=a.height){var b=this.player.getPlayerSize();if(b&&0!=b.width&&0!=b.height){var c=a.width/a.height;var d=0;for(var e=-1,f=0;f<Vta.length;f++){var k=Math.abs(b.width-Vta[f]);if(-1==e||d>=k)e=f,d=k}d=Wta[e];this.A&&g.th(this.A.element,"outline-width",Math.max(b.width,b.height)+"px");for(b=0;b<this.u.elements.length;++b)if(f=this.u.elements[b].id,e=this.o[f],k=this.G[f],e&&k){var l=k.width*c/k.aspectRatio;
f=Math.round(l*a.height);var m=a.left+Math.round(k.left*a.width),n=a.top+Math.round(k.top*a.height);g.Lh(e.element,Math.round(k.width*a.width),f);g.Bh(e.element,m,n);g.Fn(e.element,Xta);m=k.left+k.width/2;k=k.top+l/2;g.I(e.element,.5>=m&&.5>=k?"ytp-ce-top-left-quad":.5<m&&.5>=k?"ytp-ce-top-right-quad":.5>=m&&.5<k?"ytp-ce-bottom-left-quad":"ytp-ce-bottom-right-quad");g.Fn(e.element,Wta);g.I(e.element,d);(e=g.ae(document,"div","ytp-ce-expanding-overlay-body",e.element)[0])&&g.th(e,"height",f+"px")}}}}};
g.h.PG=function(a){if(this.u)if("ytp-ce-in-endscreen"==a.getId())T2(this,this.u.impressionUrls),(a=g.Sr())&&this.u.visualElement&&g.hs(a,this.u.visualElement);else{a=a.getId().substring(15);var b=this.o[a],c=this.G[a];g.I(b.element,"ytp-ce-element-show");b.element.removeAttribute("aria-hidden");b=this.player.getRootNode();g.I(b,"ytp-ce-shown");T2(this,c.impressionUrls);(b=g.Sr())&&g.hs(b,c.visualElement);this.player.O().A&&this.player.sa("endscreenelementshown",a)}};
g.h.QG=function(a){if("ytp-ce-in-endscreen"!=a.getId()){a=a.getId().substring(15);var b=this.o[a];g.En(b.element,"ytp-ce-element-show");b.element.setAttribute("aria-hidden",!0);b=this.player.getRootNode();g.En(b,"ytp-ce-shown");this.player.O().A&&this.player.sa("endscreenelementhidden",a)}};
g.h.zN=function(a){var b=this;a.target===window&&(new g.H(function(){for(var c in b.o)g.Fn(b.o[c].element,["ytp-ce-force-expand","ytp-ce-element-hover","ytp-ce-element-shadow-show"])},0)).start()};
g.h.AA=function(a,b){if(a.targetUrl&&(!b||"keypress"!=b.type||13==b.keyCode)){for(var c=b.target;c&&!g.Cn(c,"ytp-ce-element");){g.Cn(c,"subscribe-label")&&U2(this,a);if(g.Cn(c,"ytp-ce-channel-subscribe"))return;c=g.we(c)}if(!c||g.Cn(c,"ytp-ce-element-hover")){b.preventDefault();b.stopPropagation();if(c=this.o[a.id])this.eu(c,a),c.element.blur();b.ctrlKey||b.metaKey||"new"==a.yO?(U2(this,a),this.bC(),this.player.pauseVideo(),c=g.xc(R2(this,a.targetUrl)),c=g.uc(c),g.jO(c,void 0,a.Qb)):(c=this.player.getVideoData().oc,
c=(0,g.w)(this.qO,this,c,R2(this,a.targetUrl),a.Qb),c=(0,g.w)(this.bC,this,c),U2(this,a,c))}}};
g.h.qO=function(a,b,c){var d=g.bq(b);a&&d&&(d.v||d.list)?g.oT(this.player.app,d.v,c,d.list,!1,void 0):g.iO(b,c)};
g.h.jt=function(a,b){g.Cn(a.element,"ytp-ce-element-hover")||("VIDEO"==b.type||"PLAYLIST"==b.type?g.I(a.element,"ytp-ce-element-hover"):this.player.O().o?(new g.H(function(){g.I(a.element,"ytp-ce-element-hover")},200)).start():g.I(a.element,"ytp-ce-element-hover"),T2(this,b.TF),S2(this,b.id,!0))};
g.h.eu=function(a,b){g.En(a.element,"ytp-ce-element-hover");g.En(a.element,"ytp-ce-force-expand");S2(this,b.id,!1)};
g.h.bC=function(a){this.player.sendVideoStatsEngageEvent(17,a)};
var Vta=[346,426,470,506,570,640,853,1280,1920],Wta="ytp-ce-size-346 ytp-ce-size-426 ytp-ce-size-470 ytp-ce-size-506 ytp-ce-size-570 ytp-ce-size-640 ytp-ce-size-853 ytp-ce-size-1280 ytp-ce-size-1920".split(" "),Xta=["ytp-ce-top-left-quad","ytp-ce-top-right-quad","ytp-ce-bottom-left-quad","ytp-ce-bottom-right-quad"];var $sa={fQ:"current",ER:"new"};var bta={CLOSE:"close",HR:"openUrl",ND:"subscribe"},cta={ZP:"click",CLOSE:"close",TQ:"hidden",oS:"rollOut",pS:"rollOver",uS:"shown"};Z2.prototype.kc=function(){var a=dta(this,function(b){return"openUrl"==b.type&&null!=b.url});
return a?a.url:null};
var Sta={CP:"anchored",iD:"branding",CHANNEL:"channel",eQ:"cta",WQ:"highlightText",nR:"label",PLAYLIST:"playlist",aS:"popup",zS:"speech",ND:"subscribe",JS:"title",VIDEO:"video",XS:"website"},Rta={iD:"branding",QP:"card",mQ:"drawer",VQ:"highlight",uR:"marker",fS:"promotion",TEXT:"text",ZS:"widget"};a3.prototype.u=function(a,b){var c=g.De(b.target,"label");c&&g.J(c,"iv-card-poll-choice-focused",a)};
a3.prototype.B=function(a,b){var c=g.De(b.target,null,"iv-card-poll",void 0);if(c)if(a.oj)g.ce("iv-card-sign-in-button",c).click();else{var d=parseInt(Esa(b.target),10);if(null==a.De)a.choices[d].count++,a.De=d;else if(a.De!=d){var e=a.choices[a.De];e.count=Math.max(e.count-1,0);a.choices[d].count++;a.De=d}else e=a.choices[a.De],e.count=Math.max(e.count-1,0),a.De=null;kta(a,c);g.xq(this.o.videoData.be,{Yd:{action_poll_vote:1},tb:{poll_id:a.id,index:d,session_token:a.aP}});$2(this.o.logger,a.Jc.click,
void 0,5);(c=g.Sr())&&a.de&&g.ms(c,a.de)}};g.r(g3,g.z);g.h=g3.prototype;g.h.addCueRange=function(a,b,c,d,e){a=new g.ZB(a,b,{id:c});a.namespace="annotations_module";d&&this.fa.set(a,d);e&&this.ka.set(a,e);g.kL(this.context.K,[a])};
g.h.Mm=function(){this.context.u.subscribe("resize",this.Cn,this)};
g.h.xa=function(){return this.Ha};
g.h.Mk=function(a,b,c,d,e,f){this.context.o.ma(a,"click",g.Qa(this.Mo,b,c,d,e||[],f||0),this);this.context.o.ma(a,"touchstart",g.Qa(function(){this.jv=!1}),this);
this.context.o.ma(a,"touchmove",g.Qa(function(){this.jv=!0}),this)};
g.h.Mo=function(a,b,c,d,e,f){if(this.jv)return!1;f&&(f.stopPropagation(),f.preventDefault());qta(this,a,c,d,e);return!1};
g.h.show=function(){};
g.h.hide=function(){};
g.h.destroy=function(){g.te(this.xa())};
g.h.Cn=function(){};
g.h.Y=function(){this.fa.clear();this.ka.clear();g.z.prototype.Y.call(this)};g.r(k3,g3);g.h=k3.prototype;g.h.isAvailable=function(){var a;if(a=!!this.A.length)(a=this.u.getRootNode())?(a=g.Mh(a),a=173<a.width&&173<a.height):a=!1;return a};
g.h.Cn=function(){var a=this.isAvailable();g.Nh(this.xa(),a);g.J(this.context.K.getRootNode(),g.rM.IV_DRAWER_ENABLED,a);A2(this.u)};
g.h.destroy=function(){var a=g.cL(g.QK(this.u));a&&a.ct(!1,void 0);try{this.u.getRootNode().removeChild(this.D)}catch(b){}g.Qo(this.V);g.fp(this.ga);this.ea&&this.ea.dispose();this.G&&this.G.dispose();g3.prototype.destroy.call(this)};
g.h.IL=function(a){this.ba.start();a.preventDefault();a=a||window.event;var b=0;"MozMousePixelScroll"==a.type?b=0==(a.axis==a.HORIZONTAL_AXIS)?a.detail:0:window.opera?b=a.detail:b=0==a.wheelDelta%120?"WebkitTransform"in document.documentElement.style?window.chrome&&0==navigator.platform.indexOf("Mac")?a.wheelDeltaY/-30:a.wheelDeltaY/-1.2:a.wheelDelta/-1.6:a.wheelDeltaY/-3;if(a=b)this.B.scrollTop+=a};
g.h.cC=function(a){if(!g.Cn(this.u.getRootNode(),"ytp-cards-teaser-shown")){if(this.o!=a){var b=g.Sr(),c=this.o?this.o.card.Ad:this.J;b&&c&&C2(b,[c]);this.o=a;o3(this)}if(b="none"!=this.xa().style.display)2==this.context.K.getPresentingPlayerType()?b=1==this.context.K.getAdState():(b=this.context.K.getPlayerState(),c=0==b&&0===this.context.K.getCurrentTime(),b=1==b||3==b||c);b&&a.card.teaserDurationMs&&(b={teaserText:a.card.teaserText,durationMs:a.card.teaserDurationMs},(c=g.cL(g.QK(this.u)))&&c.ct(!0,
b));this.wa.isActive()||((!this.C||!this.ba.isActive()&&this.ca)&&Ata(this,a),this.wa.start(910+a.card.teaserDurationMs))}};
g.h.iO=function(a){this.C||(this.o=a,o3(this),Ata(this,a),i3(this,"YOUTUBE_DRAWER_AUTO_OPEN",!1))};
g.h.mE=function(){if(this.C){$2(this.context.logger,p3(this).Jc.close);var a=g.Sr();a&&this.N&&g.ms(a,this.N);j3(this)}};
g.h.zE=function(){g.J(this.D,"iv-drawer-scrolled",0<this.B.scrollTop)};
g.h.lG=function(){var a=g.Sr(),b=p3(this);b=b?b.Ad:this.J;a&&b&&B2(a,[b])};
g.h.kG=function(){var a=g.Sr(),b=p3(this);b=b?b.Ad:this.J;a&&b&&C2(a,[b])};
g.h.oG=function(){var a=p3(this);$2(this.context.logger,a.Jc.pC);var b=g.Sr();b&&a&&B2(b,[a.Xd,a.Ad])};
g.h.nG=function(){var a=g.Sr(),b=p3(this);a&&b&&C2(a,[b.Xd])};
g.h.mG=function(a){var b=p3(this),c=g.Sr();this.o?a?(a=this.context.logger,$2(a,b.Jc.oq),a.o.sendVideoStatsEngageEvent(4,void 0),c&&b.Xd&&g.ms(c,b.Xd)):(a=this.context.logger,$2(a,b.Jc.oq),a.o.sendVideoStatsEngageEvent(4,void 0),c&&b.Ad&&g.ms(c,b.Ad)):(a=this.context.logger,$2(a,b.Jc.oq),a.o.sendVideoStatsEngageEvent(4,void 0),c&&this.J&&g.ms(c,this.J))};g.r(q3,g3);q3.prototype.Mm=function(){g3.prototype.Mm.call(this);Bta(this)};
q3.prototype.show=function(){g3.prototype.show.call(this);var a=g.Sr(),b=this.annotation.data;a&&b&&(b=b.session_data)&&B2(a,[g.Kr(b.itct)])};
q3.prototype.hide=function(){g3.prototype.hide.call(this);var a=g.Sr(),b=this.annotation.data;a&&b&&(b=b.session_data)&&C2(a,[g.Kr(b.itct)])};g.r(r3,q3);g.h=r3.prototype;g.h.rO=function(a,b,c,d){this.A.stop();if(!this.B){var e=g.Mh(a);this.o||(g.Kh(a,e.width),g.Kh(b,e.width));g.th(c,"top",e.height-Math.max(Math.min(e.height,d)/2+10,20)+"px");g.th(c,"right","1px");this.B=!0;g.Nh(a,!0);this.C=new g.H(function(){g.I(this.xa(),"iv-branding-active")},0,this);
this.C.start()}};
g.h.SF=function(a,b){g.En(this.xa(),"iv-branding-active");this.D=new g.H((0,g.w)(function(){g.Nh(a,!1);this.o||g.Kh(b,0)},this),250);
this.D.start();this.B=!1};
g.h.show=function(){if(!this.isActive){q3.prototype.show.call(this);if(!this.G){g.I(this.xa(),"iv-branding");var a=this.annotation.data;this.u=g.ne("IMG",{"aria-label":"Channel watermark",src:a.image_url,"class":"branding-img iv-click-target",width:a.image_width,height:a.image_height});g.Nh(this.u,!1);var b=g.ne("DIV","branding-img-container",this.u);this.xa().appendChild(b);(b=this.annotation.kc())&&this.Mk(this.u,b,this.annotation.id,a.session_data);if(a.channel_name){var c=g.ne("DIV","iv-branding-context-name");
g.ye(c,a.channel_name);var d=g.ne("DIV","iv-branding-context-subscribe");if(b=a.standalone_subscribe_button_data)this.o=new g.wQ(b.subscribeText,b.subscribeCount,b.unsubscribeText,b.unsubscribeCount,!!b.enabled,!!b.classic,a.channel_id,!!b.subscribed,b.feature,a.session_data.itct,b.signinUrl,this.context.K),this.o.da(d);b=g.ne("DIV","iv-branding-context-subscribe-caret");c=g.ne("DIV","branding-context-container-inner",b,c,d);g.Nh(c,!1);d=g.ne("DIV","branding-context-container-outer",c);g.th(d,"right",
a.image_width+"px");this.xa().appendChild(d);this.A=new g.H(g.Qa(this.SF,c,d),500,this);g.A(this,this.A);this.context.o.ma(this.xa(),"mouseover",(0,g.w)(this.rO,this,c,d,b,a.image_height));this.context.o.ma(this.xa(),"mouseout",(0,g.w)(this.A.start,this.A,void 0))}this.G=!0}g.Nh(this.xa(),!0);this.isActive=!0;if(this.u){a=this.u;var e=void 0===e?0:e;b=g.Fh(a);c=g.Mh(a);b=(new g.qh(b.x,b.y,c.width,c.height)).width;g.Bh(a,b);e=new I2(a,[b,a.offsetTop],[b-b-e,a.offsetTop],200,Fsa);g.A(this,e);this.context.A.ma(e,
"begin",g.Qa(g.Nh,a,!0));e.play()}}};
g.h.hide=function(){this.isActive&&(q3.prototype.hide.call(this),g.Nh(this.xa(),!1),this.isActive=!1)};
g.h.destroy=function(){this.o&&(this.o.dispose(),this.o=null);q3.prototype.destroy.call(this)};g.r(s3,q3);g.h=s3.prototype;g.h.show=function(){this.isActive||(q3.prototype.show.call(this),this.R||(Cta(this),this.R=!0),g.Nh(this.xa(),!0),g.Uf(function(){g.En(this.xa(),"iv-promo-inactive")},100,this),this.xa().removeAttribute("aria-hidden"),this.isActive=!0,t3(this),Eta(this),Fta(this,this.G))};
g.h.hide=function(){this.isActive&&(g.I(this.xa(),"iv-promo-inactive"),this.isActive=!1,this.xa().setAttribute("aria-hidden",!0))};
g.h.Mo=function(a,b,c,d,e,f){return this.C?!1:q3.prototype.Mo.call(this,a,b,c,d,e,f)};
g.h.ws=function(a,b){b.stopPropagation();Eta(this);Fta(this,a);this.o.focus()};
g.h.wF=function(a){this.J=!0;this.ws(500,a)};
g.h.vF=function(){this.J=!1;Dta(this)};
g.h.nF=function(a){a.stopPropagation();this.hide()};
g.h.oF=function(a){a.stopPropagation();t3(this);this.C=!0;g.I(this.xa(),"iv-promo-collapsed-no-delay");this.D.start()};
g.h.destroy=function(){this.D.dispose();q3.prototype.destroy.call(this)};g.r(u3,g.BL);g.h=u3.prototype;g.h.Rc=function(a,b){if(!Ita(this.player.O().playerStyle))return null;switch(a){case "loadCustomAnnotationsXml":var c=g.z1(b);c&&v3(this,c);return!0;case "removeCustomAnnotationById":return b&&this.o&&(vta(this.o,b),A2(this.player)),!0}return null};
g.h.getOptions=function(){return Ita(this.player.O().playerStyle)?["loadCustomAnnotationsXml","removeCustomAnnotationById"]:[]};
g.h.Ip=function(){if(this.B){var a=g.WK(this.player).getVideoContentRect(!0);g.Lh(this.B.element,a.width,a.height);g.Bh(this.B.element,a.left,a.top)}if(this.o){var b=g.fL(this.player);a=this.o;b=b.width;g.J(a.D,"iv-drawer-small",426>=b);g.J(a.D,"iv-drawer-big",1280<=b)}};
g.h.dM=function(a){Jta(this,a.state);g.U(a.state,2)&&(this.fm()&&this.Uy()&&2!=this.player.getPresentingPlayerType()&&this.setCardsVisible(!1),this.ct(!1))};
g.h.load=function(){g.BL.prototype.load.call(this);Jta(this,g.VK(this.player));this.J++;var a=this.player.getVideoData(),b=a.videoId,c=(0,g.w)(this.TK,this,b,this.J),d=(0,g.w)(function(){this.D=null},this);
g.vp()&&(c=Nta(this,c));c={format:"XML",Ic:c,onError:d,Yd:{}};a.isPharma&&(c.Yd.pharma="1");c.method="POST";c.withCredentials=!0;(b=this.player.O().J.get(b))&&Ota(c,b);b=b&&(b.Hn||b.Gn);if(!a.un||b)a.be?Kta(this,a.be,c):(this.A=(0,g.w)(this.OG,this,c),this.player.addEventListener("videodatachange",this.A));g.oL(this.player,this.B.element,4);this.Ip();(b=g.BB(a))&&Tta(this,b);(b=g.CB(a))&&b.featuredChannel&&Uta(this,b.featuredChannel,b.annotationId||"branding",a.videoId||null,a.eventId||null)};
g.h.OG=function(a){var b=this.player.getVideoData();b.be&&(this.A&&(this.player.removeEventListener("videodatachange",this.A),this.A=null),Kta(this,b.be,a))};
g.h.unload=function(){g.tR(this.player.app,"annotations_module",void 0);g.zb(this.G,function(a){a.destroy()});
this.H=null;this.o&&(this.o.destroy(),this.o=null,A2(this.player));this.R=!1;this.D&&(this.D.abort(),this.D=null);this.G={};this.u.hide();g.BL.prototype.unload.call(this);g.Cu(this.B);this.A&&(this.player.removeEventListener("videodatachange",this.A),this.A=null)};
g.h.TK=function(a,b,c){this.D=null;!Mta(this,b,a)&&(a=g.nq(c)&&c.responseXML?c.responseXML:null)&&(v3(this,a),g.I(this.player.getRootNode(),"iv-module-loaded"))};
g.h.jB=function(a){a==this.player.getVideoData().videoId&&(this.loaded?Pta(this):this.load())};
g.h.fm=function(){return!!this.o&&this.o.isAvailable()};
g.h.Uy=function(){this.fm();return!!this.o&&this.o.C};
g.h.setCardsVisible=function(a,b,c){b=void 0===b?!1:b;this.fm();this.o&&(a?c?i3(this.o,c,b):i3(this.o,"YOUTUBE_DRAWER_AUTO_OPEN",b):j3(this.o))};
g.h.ct=function(a,b){this.player.T(a?"cardsteasershow":"cardsteaserhide",b)};
g.h.Y=function(){this.player.O().J.unsubscribe("vast_info_card_add",this.jB,this);g.En(this.player.getRootNode(),g.rM.IV_DRAWER_OPEN);for(var a=this.N,b=0,c=a.length;b<c;b++)g.wp(a[b]);this.N.length=0;g.BL.prototype.Y.call(this)};g.QL.annotations_module=u3;g.QL.creatorendscreen=N2;})(_yt_player);
