(function(g){var window=this;var S4=function(a,b,c){var d=b.Ca();g.J(a.element,"ytp-suggestion-set",!!d.videoId);var e=b.getPlaylistId();c=b.tc(c?c:"mqdefault.jpg");var f=b instanceof g.SA&&b.lengthSeconds?g.nM(b.lengthSeconds):null,k=!!e;e=k&&"RD"===(new g.cC(e.substr(0,2),e.substr(2))).type;var l=b instanceof g.SA?b.za:null;d={title:b.title,author:b.author,author_and_views:d.shortViewCount?b.author+" \u2022 "+d.shortViewCount:b.author,aria_label:b.ll||g.mM("Watch $TITLE",{TITLE:b.title}),duration:f,url:b.ph(),is_live:l,is_list:k,
is_mix:e,background:c?"background-image: url("+c+")":""};b instanceof g.dC&&(d.playlist_length=b.getLength());a.update(d)},T4=function(a){g.Q.call(this,{F:"div",
Z:["ytp-upnext","ytp-player-content"],P:{"aria-label":"{{aria_label}}"},L:[{F:"div",I:"ytp-cued-thumbnail-overlay-image",P:{style:"{{background}}"}},{F:"span",I:"ytp-upnext-top",L:[{F:"span",I:"ytp-upnext-header",X:"Up Next"},{F:"span",I:"ytp-upnext-title",X:"{{title}}"},{F:"span",I:"ytp-upnext-author",X:"{{author}}"}]},{F:"a",I:"ytp-upnext-autoplay-icon",P:{role:"button",href:"{{url}}","aria-label":"Play next video"},L:[{F:"svg",P:{height:"100%",version:"1.1",viewBox:"0 0 72 72",width:"100%"},L:[{F:"circle",
I:"ytp-svg-autoplay-circle",P:{cx:"36",cy:"36",fill:"#fff","fill-opacity":"0.3",r:"31.5"}},{F:"circle",I:"ytp-svg-autoplay-ring",P:{cx:"-36",cy:"36","fill-opacity":"0",r:"33.5",stroke:"#FFFFFF","stroke-dasharray":"211","stroke-dashoffset":"-211","stroke-width":"4",transform:"rotate(-90)"}},{F:"path",I:"ytp-svg-fill",P:{d:"M 24,48 41,36 24,24 V 48 z M 44,24 v 24 h 4 V 24 h -4 z"}}]}]},{F:"span",I:"ytp-upnext-bottom",L:[{F:"span",I:"ytp-upnext-cancel"},{F:"span",I:"ytp-upnext-paused",X:"Autoplay is paused"}]}]});
this.C=null;var b=this.o["ytp-upnext-cancel"];this.C=new g.Q({F:"button",Z:["ytp-upnext-cancel-button","ytp-button"],P:{tabindex:"0","aria-label":"Cancel autoplay"},X:"Cancel"});g.A(this,this.C);this.C.ma("click",this.nK,this);this.C.da(b);this.u=a;this.N=this.o["ytp-svg-autoplay-ring"];this.G=this.D=this.A=this.B=null;this.H=new g.H(this.Ln,5E3,this);g.A(this,this.H);this.J=0;g.qL(this.u,this.element,this,18788);this.M(this.o["ytp-upnext-autoplay-icon"],"click",this.YL);this.pA();this.M(a,"autonavvisibility",
this.pA);this.M(a,"mdxnowautoplaying",this.rL);this.M(a,"mdxautoplaycanceled",this.sL);this.M(a,"mdxautoplayupnext",this.KC);3==this.u.getPresentingPlayerType()&&(a=(a=g.XK(g.QK(this.u)))?a.eF():null)&&this.KC(a);g.J(this.element,"ytp-upnext-mobile",this.u.O().o)},U4=function(a,b){if(!a.A){g.Ro("a11y-announce","Up Next "+a.B.title);
a.J=(0,g.M)();a.A=new g.H((0,g.w)(a.ar,a,b),25);a.ar(b);var c=b||g.P(a.u.O().experiments,"autoplay_time")||1E4;a.u.sa("onAutonavCoundownStarted",c)}g.En(a.element,"ytp-upnext-autoplay-paused")},W4=function(a){V4(a);
a.J=(0,g.M)();a.ar();g.I(a.element,"ytp-upnext-autoplay-paused")},V4=function(a){a.A&&(a.A.dispose(),a.A=null)},X4=function(a,b){g.Q.call(this,{F:"div",
Z:["html5-endscreen","ytp-player-content",b||"base-endscreen"]});this.created=!1;this.player=a},pva=function(a){X4.call(this,a,"subscribecard-endscreen");
var b=a.getVideoData();this.u=new g.Q({F:"div",I:"ytp-subscribe-card",L:[{F:"img",I:"ytp-author-image",P:{src:b.Id}},{F:"div",I:"ytp-subscribe-card-right",L:[{F:"div",I:"ytp-author-name",X:b.author},{F:"div",I:"html5-subscribe-button-container"}]}]});g.A(this,this.u);this.u.da(this.element);this.subscribeButton=new g.wQ("Subscribe",null,"Unsubscribe",null,!0,!1,b.Pg,b.subscribed,"trailer-endscreen",null,null,a);g.A(this,this.subscribeButton);this.subscribeButton.da(this.u.o["html5-subscribe-button-container"]);
this.hide()},Y4=function(a){var b=a.O(),c=g.qt||g.wh?{style:"will-change: opacity"}:void 0,d=b.u,e=["ytp-videowall-still"];
b.o&&e.push("ytp-videowall-show-text");g.Q.call(this,{F:"a",Z:e,P:{href:"{{url}}",target:d?b.D:"","aria-label":"{{aria_label}}","data-is-live":"{{is_live}}","data-is-list":"{{is_list}}","data-is-mix":"{{is_mix}}"},L:[{F:"div",I:"ytp-videowall-still-image",P:{style:"{{background}}"}},{F:"span",I:"ytp-videowall-still-info",L:[{F:"span",I:"ytp-videowall-still-info-bg",L:[{F:"span",I:"ytp-videowall-still-info-content",P:c,L:[{F:"span",I:"ytp-videowall-still-info-title",X:"{{title}}"},{F:"span",I:"ytp-videowall-still-info-author",
X:"{{author_and_views}}"},{F:"span",I:"ytp-videowall-still-info-live",X:"Live"},{F:"span",I:"ytp-videowall-still-info-duration",X:"{{duration}}"}]}]}]},{F:"span",Z:["ytp-videowall-still-listlabel-regular","ytp-videowall-still-listlabel"],L:[{F:"span",I:"ytp-videowall-still-listlabel-icon"},"Playlist",{F:"span",I:"ytp-videowall-still-listlabel-length",L:[" (",{F:"span",X:"{{playlist_length}}"},")"]}]},{F:"span",Z:["ytp-videowall-still-listlabel-mix","ytp-videowall-still-listlabel"],L:[{F:"span",I:"ytp-videowall-still-listlabel-mix-icon"},
"Mix",{F:"span",I:"ytp-videowall-still-listlabel-length",X:" (50+)"}]}]});this.suggestion=null;this.u=d;this.api=a;this.A=new g.ur(this);g.A(this,this.A);this.ma("click",this.onClick);this.ma("keypress",this.C);this.A.M(a,"videodatachange",this.B);g.rL(a,this.element,this);this.B()},Z4=function(a){X4.call(this,a,"videowall-endscreen");
var b=this;this.K=a;this.B=0;this.stills=[];this.C=this.videoData=this.suggestions=null;this.D=this.J=!1;this.H=null;this.A=new g.PQ(this);g.A(this,this.A);this.G=new g.H(function(){g.I(b.element,"ytp-show-tiles")},0);
g.A(this,this.G);var c=new g.Q({F:"button",Z:["ytp-button","ytp-endscreen-previous"],P:{"aria-label":"Previous"},L:[g.HM()]});g.A(this,c);c.da(this.element);c.ma("click",this.qH,this);this.table=new g.Bu({F:"div",I:"ytp-endscreen-content"});g.A(this,this.table);this.table.da(this.element);c=new g.Q({F:"button",Z:["ytp-button","ytp-endscreen-next"],P:{"aria-label":"Next"},L:[g.IM()]});g.A(this,c);c.da(this.element);c.ma("click",this.pH,this);this.u=new T4(a);g.A(this,this.u);g.oL(this.player,this.u.element,
4);this.hide()},$4=function(a){return g.pL(a.player)&&a.nw()&&!a.C},qva=function(a,b){return(0,g.Dc)(b.suggestions,function(c){c=g.pM(a.K.O(),c);
g.A(a,c);return c})},a5=function(a){var b=a.mt();
b!==a.J&&(a.J=b,a.player.T("autonavvisibility"))},b5=function(a){g.BL.call(this,a);
this.endScreen=null;this.listeners=new g.ur(this);g.A(this,this.listeners);this.o=a.O();rva(a)?this.endScreen=new Z4(this.player):this.o.Ua?this.endScreen=new pva(this.player):this.endScreen=new X4(this.player);g.A(this,this.endScreen);g.oL(this.player,this.endScreen.element,4);this.VB();this.listeners.M(a,"videodatachange",this.VB,this);this.listeners.M(a,g.bC("endscreen"),this.mH,this);this.listeners.M(a,"crx_endscreen",this.nH,this)},rva=function(a){a=a.O();
return a.ya&&!a.Ua};
g.r(T4,g.Q);g.h=T4.prototype;g.h.Ln=function(){this.D&&(this.H.stop(),this.eb(this.G),this.G=null,this.D.close(),this.D=null)};
g.h.pA=function(){g.Fu(this,g.RK(this.u));g.uL(this.u,this.element,g.RK(this.u))};
g.h.PL=function(){window.focus();this.Ln()};
g.h.hide=function(){g.Q.prototype.hide.call(this)};
g.h.ar=function(a){a=a||g.P(this.u.O().experiments,"autoplay_time")||1E4;var b=Math.min((0,g.M)()-this.J,a);a=Math.min(b/a,1);this.N.setAttribute("stroke-dashoffset",-211*(a+1));1<=a&&3!=this.u.getPresentingPlayerType()?this.select(!0):this.A&&this.A.start()};
g.h.select=function(a){a=void 0===a?!1:a;if(g.O(this.u.O().experiments,"autonav_notifications")&&a&&window.Notification&&document.hasFocus){var b=Notification.permission;"default"==b?Notification.requestPermission():"granted"!=b||document.hasFocus()||(b=this.B.Ca(),this.Ln(),this.D=new Notification("Up Next",{body:b.title,icon:b.tc()}),this.G=this.M(this.D,"click",this.PL),this.H.start())}V4(this);this.u.nextVideo(!1,a)};
g.h.YL=function(a){!g.xe(this.C.element,g.gp(a))&&g.DO(a,this.u)&&this.select()};
g.h.nK=function(){g.TK(this.u,!0)};
g.h.rL=function(a){this.u.getPresentingPlayerType();this.show();U4(this,a)};
g.h.KC=function(a){this.u.getPresentingPlayerType();this.B&&this.B.Ca().videoId==a.Ca().videoId||(this.B=a,S4(this,a,"hqdefault.jpg"))};
g.h.sL=function(){this.u.getPresentingPlayerType();V4(this);this.hide()};
g.h.Y=function(){V4(this);this.Ln();g.Q.prototype.Y.call(this)};g.r(X4,g.Q);g.h=X4.prototype;g.h.create=function(){this.created=!0};
g.h.destroy=function(){this.created=!1};
g.h.nw=function(){return!1};
g.h.mt=function(){return!1};
g.h.wy=function(){return!1};g.r(pva,X4);g.r(Y4,g.Q);Y4.prototype.select=function(){var a=this.suggestion.Ca().videoId,b=this.suggestion.getPlaylistId();(g.oT(this.api.app,a,this.suggestion.Qb,b,void 0,void 0)||this.api.ia("web_player_endscreen_double_log_fix_killswitch"))&&g.tL(this.api,this.element)};
Y4.prototype.onClick=function(a){g.DO(a,this.api,this.u,this.suggestion.Qb||void 0)&&this.select()};
Y4.prototype.C=function(a){switch(a.keyCode){case 13:case 32:g.lp(a)||(this.select(),g.kp(a))}};
Y4.prototype.B=function(){var a=this.api.getVideoData(),b=this.api.O();this.u=a.oc?!1:b.u};g.r(Z4,X4);g.h=Z4.prototype;g.h.create=function(){X4.prototype.create.call(this);var a=this.player.getVideoData();a&&(this.suggestions=qva(this,a),this.videoData=a);this.Kg();this.A.M(this.player,"appresize",this.Kg);this.A.M(this.player,"onVideoAreaChange",this.Kg);this.A.M(this.player,"videodatachange",this.rH);this.A.M(this.player,"autonavchange",this.nt);this.A.M(this.player,"autonavcancel",this.oH);a=this.videoData.autonavState;a!==this.H&&this.nt(a);this.A.M(this.element,"transitionend",this.jN)};
g.h.destroy=function(){g.wr(this.A);g.Ie(this.stills);this.stills=[];this.suggestions=null;X4.prototype.destroy.call(this);g.En(this.element,"ytp-show-tiles");this.G.stop();this.H=this.videoData.autonavState};
g.h.nw=function(){return 1!==this.videoData.autonavState};
g.h.show=function(){X4.prototype.show.call(this);g.En(this.element,"ytp-show-tiles");this.player.O().o?g.vn(this.G):this.G.start();(this.D||this.C&&this.C!==this.videoData.clientPlaybackNonce)&&g.TK(this.player,!1);$4(this)?(a5(this),2===this.videoData.autonavState?this.player.O().ia("fast_autonav_in_background")&&3===this.player.getVisibilityState()?this.u.select(!0):U4(this.u):3===this.videoData.autonavState&&W4(this.u)):(g.TK(this.player,!0),a5(this))};
g.h.hide=function(){X4.prototype.hide.call(this);W4(this.u);a5(this)};
g.h.jN=function(a){g.gp(a)===this.element&&this.Kg()};
g.h.Kg=function(){if(this.suggestions&&this.suggestions.length){g.I(this.element,"ytp-endscreen-paginate");var a=g.fL(this.K,!0,this.K.isFullscreen()),b=g.VB(this.K);b&&(b=b.lc()?48:32,a.width-=2*b);var c=a.width/a.height,d=96/54,e=b=2,f=Math.max(a.width/96,2),k=Math.max(a.height/54,2),l=this.suggestions.length,m=Math.pow(2,2);var n=l*m+(Math.pow(2,2)-m);n+=Math.pow(2,2)-m;for(n-=m;0<n&&(b<f||e<k);){var q=b/2,t=e/2,u=b<=f-2&&n>=t*m,y=e<=k-2&&n>=q*m;if((q+1)/t*d/c>c/(q/(t+1)*d)&&y)n-=q*m,e+=2;else if(u)n-=
t*m,b+=2;else if(y)n-=q*m,e+=2;else break}d=!1;n>=3*m&&6>=l*m-n&&(4<=e||4<=b)&&(d=!0);m=96*b;n=54*e;c=m/n<c?a.height/n:a.width/m;c=Math.min(c,2);m*=c;n*=c;c=this.player.O().ia("web_player_no_endscreen_crop")?1:1.21;m*=g.Md(a.width/m||1,1,c);n*=g.Md(a.height/n||1,1,c);m=Math.floor(Math.min(a.width,m));n=Math.floor(Math.min(a.height,n));a=this.table.element;g.Lh(a,m,n);g.th(a,{marginLeft:m/-2+"px",marginTop:n/-2+"px"});c=this.u;f=this.suggestions[0];c.B=f;S4(c,f,"hqdefault.jpg");g.J(this.element,"ytp-endscreen-takeover",
$4(this));a5(this);m+=4;n+=4;for(f=c=0;f<b;f++)for(k=0;k<e;k++)if(q=c,t=0,d&&f>=b-2&&k>=e-2?t=1:0===k%2&&0===f%2&&(2>k&&2>f?0===k&&0===f&&(t=2):t=2),q=g.Nd(q+this.B,l),0!==t){u=this.stills[c];u||(u=new Y4(this.player),this.stills[c]=u,a.appendChild(u.element));y=Math.floor(n*k/e);var C=Math.floor(m*f/b),D=Math.floor(n*(k+t)/e)-y-4,E=Math.floor(m*(f+t)/b)-C-4;g.Bh(u.element,C,y);g.Lh(u.element,E,D);g.th(u.element,"transitionDelay",(k+f)/20+"s");g.J(u.element,"ytp-videowall-still-mini",1===t);g.J(u.element,
"ytp-videowall-still-large",2<t);t=u;q=this.suggestions[q];t.suggestion!==q&&(t.suggestion=q,u=t.api.O(),y=g.Cn(t.element,"ytp-videowall-still-large")?"hqdefault.jpg":"mqdefault.jpg",S4(t,q,y),g.By(u)&&(u=q.ph(),u=g.yd(u,g.bI({},"emb_rel_end")),t.na("url",u)),(q=(q=q.Qb)&&q.itct)&&g.sL(t.api,t.element,q));c++}g.J(this.element,"ytp-endscreen-paginate",c<l);for(b=this.stills.length-1;b>=c;b--)e=this.stills[b],g.te(e.element),g.He(e);this.stills.length=c}};
g.h.rH=function(){var a=this.player.getVideoData();this.videoData!==a&&(this.B=0,this.suggestions=qva(this,a),this.videoData=a,this.Kg())};
g.h.pH=function(){this.B+=this.stills.length;this.Kg()};
g.h.qH=function(){this.B-=this.stills.length;this.Kg()};
g.h.wy=function(){return!!this.u.A};
g.h.nt=function(a){1===a?(this.D=!1,this.C=this.videoData.clientPlaybackNonce,V4(this.u),this.Ka()&&this.Kg()):(this.D=!0,this.Ka()&&$4(this)&&(2===a?U4(this.u):3===a&&W4(this.u)))};
g.h.oH=function(a){if(a){for(a=0;a<this.stills.length;a++)g.uL(this.K,this.stills[a].element,!0);this.nt(1)}else this.C=null,this.D=!1;this.Kg()};
g.h.mt=function(){return this.Ka()&&$4(this)};g.r(b5,g.BL);g.h=b5.prototype;g.h.Wy=function(){var a=this.player.getVideoData(),b=!!(a&&a.suggestions&&a.suggestions.length);b=!rva(this.player)||b;var c=a.vj||g.Ky(a.Ta),d=g.IS(this.player.app);a=a.mutedAutoplay;return b&&!c&&!d&&!a};
g.h.Vy=function(){return this.endScreen.mt()};
g.h.ZF=function(){return this.Vy()?this.endScreen.wy():!1};
g.h.Y=function(){g.tR(this.player.app,"endscreen",void 0);g.BL.prototype.Y.call(this)};
g.h.load=function(){g.BL.prototype.load.call(this);this.endScreen.show()};
g.h.unload=function(){g.BL.prototype.unload.call(this);this.endScreen.hide();this.endScreen.destroy()};
g.h.mH=function(a){this.Wy()&&(this.endScreen.created||this.endScreen.create(),"load"===a.getId()&&this.load())};
g.h.nH=function(a){"load"===a.getId()&&this.loaded&&this.unload()};
g.h.VB=function(){g.tR(this.player.app,"endscreen",void 0);var a=this.player.getVideoData();a=new g.ZB(Math.max(1E3*(a.lengthSeconds-10),0),0x8000000000000,{id:"preload",namespace:"endscreen"});var b=new g.ZB(0x8000000000000,0x8000000000000,{id:"load",priority:6,namespace:"endscreen"});g.kL(this.player,[a,b])};g.QL.endscreen=b5;})(_yt_player);
